### ISSUE TITLE
dev: Pushover not working

### ISSUE THREAD

**Issue by gytisgreitai** [ParadoxAlarmInterface/pai#111]
```
Nov 13 19:25:59 bananapi python3[9194]: 2019-11-13 19:25:59,384 - INFO     - PAI.paradox.interfaces.interface_manager - Using Pushover Interface
Nov 13 19:25:59 bananapi python3[9194]: 2019-11-13 19:25:59,423 - ERROR    - PAI.paradox.interfaces.interface_manager - Unable to start Pushover Interface
Nov 13 19:25:59 bananapi python3[9194]: Traceback (most recent call last):
Nov 13 19:25:59 bananapi python3[9194]:   File "pai/paradox/interfaces/interface_manager.py", line 61, in start
Nov 13 19:25:59 bananapi python3[9194]:     from paradox.interfaces.text.pushover import PushoverTextInterface
Nov 13 19:25:59 bananapi python3[9194]: ImportError: cannot import name 'PushoverTextInterface'
```

**Comment by gytisgreitai** [comment]
```
Nov 14 07:00:01 bananapi python3[12649]: 2019-11-14 07:00:01,317 - ERROR    - PAI.paradox.interfaces.interface_manager - Unable to start Pushover Interface
Nov 14 07:00:01 bananapi python3[12649]: Traceback (most recent call last):
Nov 14 07:00:01 bananapi python3[12649]:   File "pai/paradox/interfaces/interface_manager.py", line 62, in start
Nov 14 07:00:01 bananapi python3[12649]:     self.register(PushoverTextInterface())
Nov 14 07:00:01 bananapi python3[12649]:   File "pai/paradox/interfaces/text/pushover.py", line 18, in __init__
Nov 14 07:00:01 bananapi python3[12649]:     super().__init__(cfg.PUSHOVER_ALLOW_EVENTS, cfg.PUSHOVER_IGNORE_EVENTS)
Nov 14 07:00:01 bananapi python3[12649]: AttributeError: 'Config' object has no attribute 'PUSHOVER_ALLOW_EVENTS'
```

Copying `PUSHOVER_ALLOW_EVENTS = [r".*"]` into `pai.conf` from `config.py` does not seem to help
