### ISSUE TITLE
EVO192 7.11.006 & IP150 4.42.002 can't run

### ISSUE THREAD

**Issue by Bl00d-B0b** [ParadoxAlarmInterface/pai#131]
Hello,

try to install on my debian system, and see the problem to run script:
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/pai/paradox/console_scripts/pai_run.py", line 28, in <module>
    main()
  File "/root/pai/paradox/console_scripts/pai_run.py", line 15, in main
    from paradox.main import main
  File "/root/pai/paradox/main.py", line 82
    logger.info(f"Starting Paradox Alarm Interface {VERSION}")

Ed

**Comment by jpbarraca** [comment]
How are you calling the script?

**Comment by Bl00d-B0b** [comment]
./run.sh

**Comment by Bl00d-B0b** [comment]
I follow manual installation instruction:
git clone https://github.com/ParadoxAlarmInterface/pai.git **success**
edit /etc/pai/pai.conf **success** 
pip3 install -r requirements.txt **success**
python3 run.py **error, no run.py file. I run run.sh instead**

**Comment by yozik04** [comment]
Python 3.6 minimum.
