### ISSUE TITLE
HomeAssistant: Platform mqtt does not generate unique IDs for zones and PGMs

### ISSUE THREAD

**Issue by clau-bucur** [ParadoxAlarmInterface/pai#175]
## Alarm system
EVO192, access mode IP150.

## Environment
- Linux, HASSIO addon

## Git branch
dev

## Describe the bug
When HomeAssistant starts the following errors are present in the logs:
Platform mqtt does not generate unique IDs. ID 0xxxfxxx_zone_Entrance_open already exists - ignoring binary_sensor.entrance
... the same for all the rest of the available zones and PGMs.

## To Reproduce
1. Install PAI addon
2. Enable "MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE: true"
3. Start addon

**Comment by yozik04** [comment]
I think @jpbarraca wrote about it that `dev` branch will generate different ids.

**Comment by yozik04** [comment]
Related to #172

**Comment by jpbarraca** [comment]
The IDs are different in dev, but maybe we need for force the update. Will check it.

**Comment by clau-bucur** [comment]
I've installed the latest DEV HassIO addon and it's returning alot of errors like this, for all the existing Paradox entities:
```
2020-10-06 17:31:11 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_alarm_control_panel_mqtt': ({'name': 'Paradox xxxx Partition PARTER', 'unique_id': 'paradox_xxxx_partition_parter', 'command_topic': 'paradox/control/partitions/PARTER', 'state_topic': 'paradox/states/partitions/PARTER/current_state', 'availability_topic': 'paradox/interface/availability', 'device': {'manufacturer': 'Paradox', 'model': 'EVO192', 'identifiers': ['Paradox', 'EVO192', 'xxxx'], 'name': 'EVO192', 'sw_version': '7.30 build 3'}, 'payload_disarm': 'disarm', 'payload_arm_home': 'arm_stay', 'payload_arm_away': 'arm', 'payload_arm_night': 'arm_sleep', 'force_update': True, 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/alarm_control_panel.py", line 117, in async_discover
    config = PLATFORM_SCHEMA(discovery_payload)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['force_update']

```

**Comment by yozik04** [comment]
I do not like this `force_update` for sensors as well.

**Comment by clau-bucur** [comment]
The issue is still there, but for other types:
```
2020-10-06 18:02:43 ERROR (MainThread) [homeassistant.util.logging] Exception in discovery_callback when dispatching 'mqtt_discovery_updated_('alarm_control_panel', 'xxx PARTER')': ({'name': 'Paradox xxx Partition PARTER', 'unique_id': 'paradox_xxx_partition_parter', 'command_topic': 'paradox/control/partitions/PARTER', 'state_topic': 'paradox/states/partitions/PARTER/current_state', 'availability_topic': 'paradox/interface/availability', 'device': {'manufacturer': 'Paradox', 'model': 'EVO192', 'identifiers': ['Paradox', 'EVO192', 'xxx'], 'name': 'EVO192', 'sw_version': '7.30 build 3'}, 'payload_disarm': 'disarm', 'payload_arm_home': 'arm_stay', 'payload_arm_away': 'arm', 'payload_arm_night': 'arm_sleep', 'force_update': True, 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/__init__.py", line 1299, in discovery_callback
    await self._discovery_update(payload)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/alarm_control_panel.py", line 170, in discovery_update
    config = PLATFORM_SCHEMA(discovery_payload)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['force_update']

2020-10-06 18:02:46 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_switch_mqtt': ({'name': 'Paradox xxx Zone Intrare Bypass', 'unique_id': 'paradox_xxx_zone_intrare_bypass', 'state_topic': 'paradox/states/zones/Intrare/bypassed', 'availability_topic': 'paradox/interface/availability', 'command_topic': 'paradox/control/zones/Intrare', 'payload_on': 'bypass', 'payload_off': 'clear_bypass', 'state_on': 'True', 'state_off': 'False', 'device': {'manufacturer': 'Paradox', 'model': 'EVO192', 'identifiers': ['Paradox', 'EVO192', 'xxx'], 'name': 'EVO192', 'sw_version': '7.30 build 3'}, 'force_update': True, 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/switch.py", line 86, in async_discover
    config = PLATFORM_SCHEMA(discovery_payload)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['force_update']

```

**Comment by jpbarraca** [comment]
for clean environments the force_update is not mandatory, but results in nicer charts as it increases the amount of data published. I didn't had that error. What version of HA do you have?

**Comment by yozik04** [comment]
From his log it is for `bypass`. I have fixed for `partition` already.

**Comment by clau-bucur** [comment]
I've restarted DEV addon (I switched to release Addon while this issue is fixed) and here is the encrypted log.
[home-assistant.log](https://github.com/ParadoxAlarmInterface/pai/files/5336086/home-assistant.log)

**Comment by yozik04** [comment]
This feature does not exist in release addon. You need to cleanup mqtt before testing again.
How you updated dev? Removed and readded?

**Comment by clau-bucur** [comment]
Yes, I update DEV by uninstalling the addon and installing it again. Would love to have a better way :D
OK, I stopped addon, removed all MQTT messages, rebooted HA, started DEV addon.
It generates errors when discovers new alarm panels and new switches (the errors repeat for all existing partitions and switches):
```
2020-10-07 09:56:47 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_alarm_control_panel_mqtt': ({'name': 'Paradox xxxxx Partition ETAJ', 'unique_id': 'paradox_xxxxx_partition_etaj', 'command_topic': 'paradox/control/partitions/ETAJ', 'state_topic': 'paradox/states/partitions/ETAJ/current_state', 'availability_topic': 'paradox/interface/availability', 'device': {'manufacturer': 'Paradox', 'model': 'EVO192', 'identifiers': ['Paradox', 'EVO192', 'xxxxx'], 'name': 'EVO192', 'sw_version': '7.30 build 3'}, 'payload_disarm': 'disarm', 'payload_arm_home': 'arm_stay', 'payload_arm_away': 'arm', 'payload_arm_night': 'arm_sleep', 'force_update': True, 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/alarm_control_panel.py", line 117, in async_discover
    config = PLATFORM_SCHEMA(discovery_payload)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['force_update']

2020-10-07 09:56:48 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_switch_mqtt': ({'name': 'Paradox xxxxx Zone Intrare Bypass', 'unique_id': 'paradox_xxxxx_zone_intrare_bypass', 'state_topic': 'paradox/states/zones/Intrare/bypassed', 'availability_topic': 'paradox/interface/availability', 'command_topic': 'paradox/control/zones/Intrare', 'payload_on': 'bypass', 'payload_off': 'clear_bypass', 'state_on': 'True', 'state_off': 'False', 'device': {'manufacturer': 'Paradox', 'model': 'EVO192', 'identifiers': ['Paradox', 'EVO192', 'xxxxx'], 'name': 'EVO192', 'sw_version': '7.30 build 3'}, 'force_update': True, 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/switch.py", line 86, in async_discover
    config = PLATFORM_SCHEMA(discovery_payload)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['force_update']

```

**Comment by yozik04** [comment]
I have removed all `force_update` parameters from the config

**Comment by clau-bucur** [comment]
Updated it. No `force_update` errors in the log anymore, but now the `paradox/control` topic is not created anylonger.
![image](https://user-images.githubusercontent.com/47672949/95377183-e3136280-08ea-11eb-9db8-7f2c779bd6fe.png)

This renders the HA entities dead.

**Comment by clau-bucur** [comment]
Looks good now!

**Comment by clau-bucur** [comment]
It works ok since 9 days now.
