### ISSUE TITLE
SP7000 error using Openhab

### ISSUE THREAD

**Issue by DND202021** [ParadoxAlarmInterface/pai#179]
Panel SP7000 Ver. 7.00.012
IP150 Ver. 5.02.019

I get the following error when trying to connect using IP150 to and SP7000 panel: 

2020-09-28 17:59:52.440 [INFO ] [nal.communication.CommunicationState] - Login - Login to IP150 - OK
2020-09-28 17:59:57.022 [INFO ] [nal.communication.CommunicationState] - Successfully established communication with the panel.
2020-09-28 17:59:57.223 [INFO ] [l.handlers.ParadoxIP150BridgeHandler] - Found SP7000 panel type.
2020-09-28 17:59:57.232 [INFO ] [l.communication.AbstractCommunicator] - Stopping communication to Paradox system

020-09-28 18:00:00.239 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
org.openhab.binding.paradoxalarm.internal.exceptions.ParadoxRuntimeException: Unsupported panel type: SP7000
	at org.openhab.binding.paradoxalarm.internal.communication.ParadoxBuilderFactory.createBuilder(ParadoxBuilderFactory.java:40) ~[?:?]
	at org.openhab.binding.paradoxalarm.internal.handlers.ParadoxIP150BridgeHandler.createDiscoveredCommunicatorJob(ParadoxIP150BridgeHandler.java:166) ~[?:?]
	at org.openhab.binding.paradoxalarm.internal.handlers.ParadoxIP150BridgeHandler.lambda$4(ParadoxIP150BridgeHandler.java:156) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by yozik04** [comment]
Wrong project. It is not openhab’s binding code.

**Comment by DND202021** [comment]
My bad, I realised that afterward, my appologies.
