### ISSUE TITLE
Python Dump starting Addon in HASSIO

### ISSUE THREAD

**Issue by michielv** [ParadoxAlarmInterface/pai#185]
When starting addon in Home Assistant I get the following dump:

Error parsing configuration: Invalid value type <class 'NoneType'> for config argument SERIAL_PORT.

## Alarm system
 Magellan MG5050 with IP150 >V4

## Environment
Home Assistant 0.116.4 on HASSIO
arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.14
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.69
python_version | 3.8.5
supervisor | 249
timezone | Africa/Johannesburg
version | 0.116.4
virtualenv | false

### Git branch

Paradox Alarm Interface
Current version: 2.2.3
## Logs (if required)
Error parsing configuration: Invalid value type <class 'NoneType'> for config argument SERIAL_PORT. Allowed are: [<class 'str'>]
Attempting to load configuration from /data/options.json
Traceback (most recent call last):
  File "/usr/local/bin/pai-service", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/paradox/console_scripts/pai_run.py", line 36, in main
    main(args)
  File "/usr/local/lib/python3.7/site-packages/paradox/main.py", line 118, in main
    cfg.load()
  File "/usr/local/lib/python3.7/site-packages/paradox/config.py", line 371, in load
    raise (Exception(err))
Exception: Error parsing configuration: Invalid value type <class 'NoneType'> for config argument SERIAL_PORT. Allowed are: [<class 'str'>]

**Comment by michielv** [comment]
Apologies I missed the glaring issue that I had a null value in SERIAL_PORT: under my configuration.
