### ISSUE TITLE
Unable to connect to my Paradox EVOHD

### ISSUE THREAD

**Issue by sebglon** [ParadoxAlarmInterface/pai#240]
## Alarm system
Describe your panel model EVOHD with IP150 and SWAN WITH 2 HD88 on the same site

## Environment
- LINUX and Docker
- Python version

## Git branch
Which Git branch you use. Did you tried "dev" branch? Please try before posting.

I use the latest docker image

## Describe the bug
Failed to connect to interface

2021-05-07 13:31:48,443 - ERROR    - MainThread - PAI.paradox.connections.ip.connection - Unhandled exception while connecting (try 3/3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/connections/ip/connection.py", line 30, in connect
    await self._try_connect()
  File "/usr/local/lib/python3.9/site-packages/paradox/connections/ip/connection.py", line 147, in _try_connect
    await self.stun_session.connect()
  File "/usr/local/lib/python3.9/site-packages/paradox/connections/ip/stun_session.py", line 49, in connect
    module["panelSerial"]
TypeError: string indices must be integers

## To Reproduce
1. Start script 'docker run -it --rm --name pai -v ~/docker/pai/config:/etc/pai:ro -v ~/docker/pai/log:/var/log/pai -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro -e "TZ=EUROPE/Tallinn" --user $(id -u):$(id -g)  -P paradoxalarminterface/pai:latest'

With my config
```
IP_CONNECTION_PASSWORD = 'paradox' # IP Module password. "paradox" is default.
IP_CONNECTION_SITEID = 'maison-reze' 		# SITE ID. IF defined, connection will be made through this method.
IP_CONNECTION_EMAIL = 'sebglon@gmail.com' 		# Email registered in the site
IP_CONNECTION_PANEL_SERIAL =  'xxxxxxx'  # Use a specific panel. Set it to None to use the first
```
2. Do something '....'
3. See error

## Site info
Extract of my site info
```
                    "swport": 10000,
                    "name": null,
                    "type": "IP150",
                    "panelSerial": "0700a21f",
                    "xoraddr": "000185e2028cf150",
                    "API": null,
                    "ipAddress": "0.0.0.0"
```

**Comment by sebglon** [comment]
For me we have an issue here: https://github.com/ParadoxAlarmInterface/pai/blob/7d53cc63d27615c9805fc0d25dbf3aca97786189/paradox/connections/ip/stun_session.py#L44

Because we not filter the site by type="IP150"

**Comment by sebglon** [comment]
Nice. Work as expected.
Thanks
