### ISSUE TITLE
PAI Restart when connected to panel

### ISSUE THREAD

**Issue by pauldingo** [ParadoxAlarmInterface/pai#251]
I am using a IP150 module, version 20, firmware 1.34 and SP7000 version 4.94
HA is connecting and Authentication but I am getting what could be a code error when trying to read the panel
Please see logs
2021-06-13 15:13:13,882 - INFO     - PAI - Starting Paradox Alarm Interface 2.5.3
2021-06-13 15:13:13,882 - INFO     - PAI - Config loaded from /data/options.json
2021-06-13 15:13:13,882 - INFO     - PAI - Console Log level set to 20
2021-06-13 15:13:13,965 - INFO     - PAI.paradox.interfaces - Starting BasicMQTTInterface Interface
2021-06-13 15:13:13,968 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT loop started
2021-06-13 15:13:13,971 - INFO     - PAI.paradox.interfaces - Starting HomeAssistantMQTTInterface Interface
2021-06-13 15:13:13,975 - INFO     - PAI.paradox.interfaces.ip_interface.interface - Starting IPInterface Interface
2021-06-13 15:13:13,977 - INFO     - PAI - Starting...
2021-06-13 15:13:13,977 - INFO     - PAI.paradox.paradox - Connecting to interface
2021-06-13 15:13:13,978 - INFO     - PAI.paradox.paradox - Using IP Connection
2021-06-13 15:13:14,188 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2021-06-13 15:13:14,191 - INFO     - PAI.paradox.connections.connection - Connection established
2021-06-13 15:13:14,191 - INFO     - PAI.paradox.interfaces.ip_interface.interface - IP Interface: serving on ('0.0.0.0', 10000)
2021-06-13 15:13:14,192 - INFO     - PAI.paradox.interfaces.ip_interface.interface - IP Interface started
2021-06-13 15:13:14,193 - INFO     - PAI.paradox.connections.ip.commands - Authenticating with IP Module
2021-06-13 15:13:14,200 - INFO     - PAI.paradox.connections.ip.commands - Authentication Success. IP(IP150) Module version 20, firmware: 1.34, serial: 710290a8
2021-06-13 15:13:14,214 - INFO     - PAI.paradox.connections.ip.commands - Session successfully established with IP Module
2021-06-13 15:13:14,214 - INFO     - PAI.paradox.paradox - Connecting to Panel
2021-06-13 15:13:14,311 - INFO     - PAI.paradox.paradox - Panel Identified SP7000 version 4.94 build 0
2021-06-13 15:13:14,311 - INFO     - PAI.paradox.paradox - Initiating panel connection
2021-06-13 15:13:14,426 - ERROR    - PAI - Restarting
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/main.py", line 81, in run_loop
    if await alarm.full_connect():
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 211, in full_connect
    if not await self.connect():
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 191, in connect
    result = await self.panel.initialize_communication(cfg.PASSWORD)
  File "/usr/local/lib/python3.9/site-packages/paradox/hardware/spectra_magellan/panel.py", line 174, in initialize_communication
    encoded_password = self.encode_password(password)
  File "/usr/local/lib/python3.9/site-packages/paradox/hardware/panel.py", line 114, in encode_password
    return binascii.a2b_hex(password.zfill(4))
binascii.Error: Non-hexadecimal digit found

Config is as follows
LOGGING_LEVEL_CONSOLE: 20
LOGGING_LEVEL_FILE: 40
CONNECTION_TYPE: IP
SERIAL_PORT: /dev/ttyUSB0
SERIAL_BAUD: 9600
IP_CONNECTION_HOST: 192.168.1.25
IP_CONNECTION_PORT: 10000
IP_CONNECTION_PASSWORD: MYPASSWORD
KEEP_ALIVE_INTERVAL: 10
LIMITS:
  zone: auto
  user: 1-10
  door: ''
  pgm: 1-5
  partition: auto
  module: ''
  repeater: ''
  keypad: ''
  key-switch: ''
SYNC_TIME: true
SYNC_TIME_MIN_DRIFT: 120
PASSWORD: MYPASSWORD
MQTT_ENABLE: true
MQTT_HOST: 192.168.1.180
MQTT_PORT: 1883
MQTT_KEEPALIVE: 60
MQTT_USERNAME: MYADMIN
MQTT_PASSWORD: MQTTPASSWORD
MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE: true
COMMAND_ALIAS:
  arm: partition all arm
  disarm: partition all disarm
MQTT_COMMAND_ALIAS:
  armed_home: arm_stay
  armed_night: arm_sleep
  armed_away: arm
  disarmed: disarm
HOMEASSISTANT_NOTIFICATIONS_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
PUSHBULLET_CONTACTS: []
PUSHBULLET_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock

  - live,tamper
PUSHOVER_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
PUSHOVER_BROADCAST_KEYS: []
SIGNAL_CONTACTS: []
SIGNAL_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
GSM_CONTACTS: []
GSM_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
IP_INTERFACE_ENABLE: true
IP_INTERFACE_PASSWORD: MYPASSWORD
DUMMY_EVENT_FILTERS: []

Looking for help as to where to look.
HA is on a Intel NUC Core 2021.6.4 Supervor version 2012.06.0
Can i also ask clarity for line 22, is the password the IP module password or the panel code? (I have it set for the IP150 password).

**Comment by pauldingo** [comment]
Further update. I am seeing a bug in the options/configuration when the IP150 password is different to the PC password for the Panel and I get the following error.
"Failed to save add-on configuration, not a valid value. Got {'LOGGING_LEVEL_CONSOLE': 20, 'LOGGING_LEVEL_FILE': 40, 'CONNECTION_TYPE': 'IP', 'SERIAL_PORT': '/dev/ttyUSB0', 'SERIAL_BAUD': 9600, 'IP_CONNECTION_HOST': '192.168.1.25', 'IP_CONNECTION_PORT': 10000, 'IP_CONNECTION_PASSWORD': 'MYPASSWORD', 'KEEP_ALIVE_INTERVAL': 10, 'LIMITS': {'zone': 'auto', 'user': '1-10', 'door': '', 'pgm': '1-5', 'partition': 'auto', 'module': '', 'repeater': '', 'keypad': '', 'key-switch': ''}, 'SYNC_TIME': True, 'SYNC_TIME_MIN_DRIFT': 120, 'PASSWORD': 1234, 'MQTT_ENABLE':.
The unit will connect correctly with the IP150 but not the panel as it will not accept the 1234 in the config file for the Panel PC password.

**Comment by pauldingo** [comment]
FIXED, you need to ensure the PC connection password, LINE 22 of the configuration is in ' ' marks
