### ISSUE TITLE
Swan connection doesnt work why?

### ISSUE THREAD

**Issue by ukrolelo** [ParadoxAlarmInterface/pai#255]
panel fw 7.31.1
EVO192
IP150+ 5.03.000
PCS25G 4.21.001

## Environment
HASS OS, PAI addon

## Git branch
latest stable

## Describe the bug
Cant connect

## Logs
```
,029 - INFO     - PAI.paradox.interfaces - Starting HomeAssistantMQTTInterface Interface
2021-06-28 22:29:20,029 - INFO     - PAI - Starting...
2021-06-28 22:29:20,029 - INFO     - PAI.paradox.paradox - Connecting to interface
2021-06-28 22:29:20,029 - INFO     - PAI.paradox.paradox - Using IP Connection
2021-06-28 22:29:20,075 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2021-06-28 22:29:20,075 - INFO     - PAI.paradox.connections.ip.stun_session - Connecting to Site: xxxxx
2021-06-28 22:29:20,075 - INFO     - PAI.paradox.connections.ip.stun_session - Getting site info
2021-06-28 22:29:20,961 - INFO     - PAI.paradox.connections.ip.stun_session - Connected to Site: xxxx
2021-06-28 22:29:20,961 - INFO     - PAI.paradox.connections.connection - Connection established
2021-06-28 22:29:20,961 - INFO     - PAI.paradox.connections.ip.commands - Authenticating with IP Module
2021-06-28 22:29:21,031 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT Broker Connected
2021-06-28 22:29:22,964 - ERROR    - PAI.paradox.connections.ip.connection - Timeout while establishing connection (try 1/3): 
2021-06-28 22:29:22,964 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 2/3
2021-06-28 22:29:22,965 - INFO     - PAI.paradox.connections.ip.stun_session - Connecting to Site: xxx
2021-06-28 22:29:23,226 - INFO     - PAI.paradox.connections.ip.stun_session - Connected to Site: xxx
2021-06-28 22:29:23,227 - INFO     - PAI.paradox.connections.connection - Connection established
2021-06-28 22:29:23,227 - INFO     - PAI.paradox.connections.ip.commands - Authenticating with IP Module
2021-06-28 22:29:23,227 - ERROR    - PAI.paradox.connections.protocols - Connection was closed: [Errno 104] Connection reset by peer
2021-06-28 22:29:23,228 - ERROR    - PAI.paradox.connections.connection - Connection was lost
2021-06-28 22:29:25,229 - ERROR    - PAI.paradox.connections.ip.connection - Timeout while establishing connection (try 2/3): 
2021-06-28 22:29:25,229 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 3/3
2021-06-28 22:29:25,229 - INFO     - PAI.paradox.connections.ip.stun_session - Connecting to Site: xxx
```

config
```
LOGGING_LEVEL_CONSOLE: 20
LOGGING_LEVEL_FILE: 40
CONNECTION_TYPE: IP
SERIAL_PORT: /dev/ttyUSB0
SERIAL_BAUD: 9600
IP_CONNECTION_HOST: 127.0.0.1
IP_CONNECTION_PORT: 10000
IP_CONNECTION_PASSWORD: paradox
KEEP_ALIVE_INTERVAL: 10
LIMITS:
  zone: auto
  user: 1-10
  door: ''
  pgm: 1-5
  partition: auto
  module: ''
  repeater: ''
  keypad: ''
  key-switch: ''
SYNC_TIME: true
SYNC_TIME_MIN_DRIFT: 120
PASSWORD: 'mypanelcode'
MQTT_ENABLE: true
MQTT_HOST: core-mosquitto
MQTT_PORT: 1883
MQTT_KEEPALIVE: 60
MQTT_USERNAME: xxx
MQTT_PASSWORD: yyy
MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE: true
COMMAND_ALIAS:
  arm: partition all arm
  disarm: partition all disarm
MQTT_COMMAND_ALIAS:
  armed_home: arm_stay
  armed_night: arm_sleep
  armed_away: arm
  disarmed: disarm
HOMEASSISTANT_NOTIFICATIONS_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
PUSHBULLET_CONTACTS: []
PUSHBULLET_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
PUSHOVER_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
PUSHOVER_BROADCAST_KEYS: []
SIGNAL_CONTACTS: []
SIGNAL_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
GSM_CONTACTS: []
GSM_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
IP_INTERFACE_ENABLE: false
IP_INTERFACE_PASSWORD: paradox
DUMMY_EVENT_FILTERS: []
IP_CONNECTION_SITEID: mysiteid
IP_CONNECTION_EMAIL: myemail
IP_CONNECTION_PANEL_SERIAL: ''
```

**Comment by yozik04** [comment]
Because of wrong PC Password :)

**Comment by ukrolelo** [comment]
But i am trying to use the swan, so i need to put pc password None?  :O

**Comment by yozik04** [comment]
You still need PC Password for SWAN 😆

**Comment by ukrolelo** [comment]
its my panel password that i use in inside gold or it must be the master? :-PPPPP

**Comment by yozik04** [comment]
It is you need to read documentation a bit. It is other password. Nor master nor User nor installer. PC Password

**Comment by ukrolelo** [comment]
> It is you need to read documentation a bit. It is other password. Nor master nor User nor installer. PC Password

Okay i put 0000 and i givving up on swan :smile: will hope to catch the master code,i have sent the email.
```
2021-06-29 13:13:42,510 - INFO     - PAI.paradox.connections.ip.stun_session - Getting site info
2021-06-29 13:13:43,074 - ERROR    - PAI.paradox.connections.ip.connection - Unhandled exception while connecting (try 1/3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/connections/ip/connection.py", line 30, in connect
    await self._try_connect()
  File "/usr/local/lib/python3.9/site-packages/paradox/connections/ip/connection.py", line 147, in _try_connect
    await self.stun_session.connect()
  File "/usr/local/lib/python3.9/site-packages/paradox/connections/ip/stun_session.py", line 44, in connect
    raise ConnectToSiteFailed("Unable to find module with desired panel serial")
```
