### ISSUE TITLE
I can't connect.

### ISSUE THREAD

**Issue by Tomcatnet** [ParadoxAlarmInterface/pai#268]
I can't connect.

I think it is a problem with the configuration.
can anybody help me???
it is a MG5050 firm 7.14.002
with an IP150 firm 5.02.045
this is the configuration I have

LOGGING_LEVEL_CONSOLE: 20
LOGGING_LEVEL_FILE: 40
CONNECTION_TYPE: IP
SERIAL_PORT: / dev / ttyUSB0
SERIAL_BAUD: 9600
IP_CONNECTION_HOST: 192.168.1.XXX
IP_CONNECTION_PORT: 10000
IP_CONNECTION_PASSWORD: paradox
KEEP_ALIVE_INTERVAL: 10
LIMITS:
  zone: auto
  user: 1-10
  door: ''
  pgm: 1-5
  partition: auto
  module: ''
  repeater: ''
  keypad: ''
  key-switch: ''
SYNC_TIME: true
SYNC_TIME_MIN_DRIFT: 120
PASSWORD: 'xxxx'
MQTT_ENABLE: true
MQTT_HOST: core-mosquitto
MQTT_PORT: 1883
MQTT_KEEPALIVE: 60
MQTT_USERNAME: xxxx
MQTT_PASSWORD: xxxx
MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE: true
COMMAND_ALIAS:
  arm: partition all arm
  disarm: partition all disarm
MQTT_COMMAND_ALIAS:
  armed_home: arm_stay
  armed_night: arm_sleep
  armed_away: arm
  disarmed: disarm
HOMEASSISTANT_NOTIFICATIONS_EVENT_FILTERS:
  - live, alarm, -restore
  - live, trouble, -clock
  - live, tamper
PUSHBULLET_CONTACTS: []
PUSHBULLET_EVENT_FILTERS:
  - live, alarm, -restore
  - live, trouble, -clock
  - live, tamper
PUSHOVER_EVENT_FILTERS:
  - live, alarm, -restore
  - live, trouble, -clock
  - live, tamper
PUSHOVER_BROADCAST_KEYS: []
SIGNAL_CONTACTS: []
SIGNAL_EVENT_FILTERS:
  - live, alarm, -restore
  - live, trouble, -clock
  - live, tamper
GSM_CONTACTS: []
GSM_EVENT_FILTERS:
  - live, alarm, -restore
  - live, trouble, -clock
  - live, tamper
IP_INTERFACE_ENABLE: false
IP_INTERFACE_PASSWORD: paradox
DUMMY_EVENT_FILTERS: []

This is the error that gives

paradox.exceptions.CodeLockout
2021-11-18 23: 51: 00,590 - ERROR - PAI.paradox.paradox - Got ERROR Message: Partition in code lockout (too many bad entries)
2021-11-18 23: 51: 00,591 - ERROR - PAI.paradox.lib.handlers - Exception caught during message handling
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler (data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle (data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout ()
paradox.exceptions.CodeLockout
2021-11-18 23: 51: 00,594 - ERROR - PAI.paradox.exceptions - Unhandled exception in async loop (<_ UnixSelectorEventLoop running = True closed = False debug = False>):
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler (data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle (data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout ()
paradox.exceptions.CodeLockout
Task exception was never retrieved
future: <Task finished name = 'Task-138' chorus = <HandlerRegistry.handle () done, defined at /usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py:101> exception = CodeLockout ()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler (data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle (data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout ()
paradox.exceptions.CodeLockout
2021-11-18 23: 51: 01,493 - ERROR - PAI.paradox.paradox - Timeout while connecting to panel. Is an other connection active?
2021-11-18 23: 51: 01,493 - ERROR - PAI - Unable to connect to alarm
2021-11-18 23: 51: 03,612 - INFO - PAI - Captured signal SIGTERM. Exiting
2021-11-18 23: 51: 03,612 - INFO - PAI.paradox.paradox - Disconnecting from the Alarm Panel
2021-11-18 23: 51: 03,613 - INFO - PAI.paradox.paradox - Clean Session
2021-11-18 23: 51: 03,613 - INFO - PAI.paradox.paradox - Cleaning previous session. Closing connection
2021-11-18 23: 51: 03,617 - ERROR - PAI.paradox.connections.protocols - Connection was closed: None
2021-11-18 23: 51: 03,617 - ERROR - PAI.paradox.connections.connection - Connection was lost
2021-11-18 23: 51: 03,619 - INFO - PAI.paradox.paradox - Disconnected from the Alarm Panel
2021-11-18 23: 51: 03,620 - INFO - PAI.paradox.interfaces.interface_manager - Stopping all interfaces
2021-11-18 23: 51: 03,620 - INFO - PAI.paradox.interfaces.interface_manager - Stopping BasicMQTTInterface
2021-11-18 23: 51: 03,621 - INFO - PAI.paradox.interfaces.interface_manager - Stopping HomeAssistantMQTTInterface
2021-11-18 23: 51: 03,624 - INFO - PAI.paradox.interfaces.mqtt.core - MQTT Broker Disconnected
2021-11-18 23: 51: 03,625 - INFO - PAI.paradox.interfaces.mqtt.core - MQTT loop stopped
2021-11-18 23: 51: 03,625 - INFO - PAI - Good bye!

Thankshe feature -->

**Comment by yozik04** [comment]
Wrong password. You did so many attempts so panel locked out. Wait for an hour and try again with the right password.

**Comment by Tomcatnet** [comment]
Right, I had the wrong PC Password.

Thanks

**Comment by Tomcatnet** [comment]
when I configure the alarm with Panel ID and PC Password, it is when I get the error.
I imagine it is because the Panel ID is not there.
How can I add it to the configuration?

Thanks

**Comment by yozik04** [comment]
Panel ID is picked up automatically. Password is wrong. Make sure you have read the notes about 0 in the password.

**Comment by woodgieboodgie** [comment]
Hi,

Experiencing the same error and have waited the 60mins for the panel to reset. Confirmed the module is on ...0.8.
Just to confirm that an IP150+ has the default password of 'paradox' and I dont need the usercode or panelID? I am unsure what the PC password is but do i need that for PAI plugin?

**Comment by yozik04** [comment]
Yes you need PC password. and IP150+ password.
PC password is not user code and not Installer code. it is different.

**Comment by woodgieboodgie** [comment]
Thanks. I notice the PC password can be set from the panels, some with menu codes that are 4 digits and others that are 3.
Would it be easiest to try and set it back to '0000' from there or do i need to install Babyware and go through that process?

**Comment by yozik04** [comment]
it is absolutely your choice =) What is more comfortable for you.

**Comment by woodgieboodgie** [comment]
OK.  One last question re the IP150.. after a reset it should be back to 'paradox' correct? because i cant log into it using 'paradox' via a browser but a user code does allow me to enter the menu (but installer code doesnt)

**Comment by yozik04** [comment]
Their Web UI is an another story and is not anyhow related to PAI.
I think you can not even change that "paradox" password in the latest IP150+ firmwares. It is security feature 🤣. Installer code is for programming via the panel only (my assumption).

**Comment by woodgieboodgie** [comment]
is there a way that i can turn logging on and validate that i am authenticating successfully with the IP150 and the failure is at the PC password?  right now its only a guess
