### ISSUE TITLE
Problem with MQTT_USE_NUMERIC_STATES

### ISSUE THREAD

**Issue by tomplus** [ParadoxAlarmInterface/pai#287]
Hi

I'd like to use the option MQTT_USE_NUMERIC_STATES=True but it causes:

```
future: <Task finished name='Task-34539' coro=<PubSub.sendMessage() done, defined at /usr/local/lib/python3.9/site-packages/paradox/lib/ps.py:57> exception=TypeError("int() argument must be a string, a bytes-like object or a number, not 'datetime.datetime'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/ps.py", line 58, in sendMessage
    return await asyncio.gather(
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/ps.py", line 28, in call
    result = self.callback(**kwargs2)
  File "/usr/local/lib/python3.9/site-packages/paradox/interfaces/mqtt/basic.py", line 416, in _handle_panel_change
    self._publish(
  File "/usr/local/lib/python3.9/site-packages/paradox/interfaces/mqtt/basic.py", line 448, in _publish
    publish_value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.datetime'
```

probably triggered by:
```
PAI.paradox.data.memory_storage - Change system/date/time from 2022-03-27 23:37:57 to 2022-03-27 23:38:09
```

Are you willing to add an additional type check here?

https://github.com/ParadoxAlarmInterface/pai/blob/3f46978723fee83211f26f93a3f3dc6d2227750f/paradox/interfaces/mqtt/basic.py#L447-L450

datetime can be convert to epoch time, float can be preserved as a float etc. What do you think?

Thanks!

**Comment by yozik04** [comment]
Hah. Looks like no one used this option for a looooong time... I am sure it will crash somewhere else too.

**Comment by yozik04** [comment]
I would just wrap it in `try: catch TypeError` and fall back to default behavior. Can you make PR and verify it yourself?

**Comment by tomplus** [comment]
It should be enough.. I'll do it soon. Thanks.
