### ISSUE TITLE
Cant connect to panel

### ISSUE THREAD

**Issue by r11a** [ParadoxAlarmInterface/pai#304]
Hello,

I'm getting the following log:

paradox.exceptions.CodeLockout
Task exception was never retrieved
future: <Task finished name='Task-852' coro=<HandlerRegistry.handle() done, defined at /usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py:101> exception=CodeLockout()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout()
paradox.exceptions.CodeLockout

Home Assistant 2022.8.2
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220802.0 - latest

**Comment by yozik04** [comment]
Hello. Wrong code entered multiple times locks the panel for some time.

**Comment by r11a** [comment]
LOGGING_LEVEL_CONSOLE: 20
LOGGING_LEVEL_FILE: 40
CONNECTION_TYPE: IP
SERIAL_PORT: /dev/ttyUSB0
SERIAL_BAUD: 9600
IP_CONNECTION_HOST: 192.168.1.114
IP_CONNECTION_PORT: 10000
IP_CONNECTION_PASSWORD: paradox
KEEP_ALIVE_INTERVAL: 10
LIMITS:
  zone: auto
  user: 1-10
  door: ''
  pgm: 1-5
  partition: auto
  module: ''
  repeater: ''
  keypad: ''
  key-switch: ''
SYNC_TIME: true
SYNC_TIME_MIN_DRIFT: 120
**PASSWORD: '0000'**
MQTT_ENABLE: true
MQTT_HOST: core-mosquitto
MQTT_PORT: 1883
MQTT_KEEPALIVE: 60
MQTT_USERNAME: XXXXX
MQTT_PASSWORD: XXXXXX
MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE: true
COMMAND_ALIAS:
  arm: partition all arm
  disarm: partition all disarm
MQTT_COMMAND_ALIAS:
  armed_home: arm_stay
  armed_night: arm_sleep
  armed_away: arm
  disarmed: disarm
HOMEASSISTANT_NOTIFICATIONS_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
HOMEASSISTANT_PUBLISH_PARTITION_PROPERTIES:
  - target_state
  - current_state
HOMEASSISTANT_PUBLISH_ZONE_PROPERTIES:
  - open
  - tamper
PUSHBULLET_CONTACTS: []
PUSHBULLET_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
PUSHOVER_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
PUSHOVER_BROADCAST_KEYS: []
SIGNAL_CONTACTS: []
SIGNAL_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
GSM_CONTACTS: []
GSM_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
IP_INTERFACE_ENABLE: false
IP_INTERFACE_PASSWORD: paradox
DUMMY_EVENT_FILTERS: []

This is my code
PASSWORD: '0000' and its the correct panel code

**Comment by yozik04** [comment]
Did you tried `aaaa`?

**Comment by proasnet** [comment]
Hi. I have a similar problem. Sometime is working, nut now 5 days not. Restarted addon, restarted ip module IP100. Nothing.
Log is
2022-08-08 17:53:42,336 - INFO     - PAI - Starting Paradox Alarm Interface 3.0.1
2022-08-08 17:53:42,336 - INFO     - PAI - Config loaded from /data/options.json
2022-08-08 17:53:42,337 - INFO     - PAI - Console Log level set to 20
2022-08-08 17:53:42,470 - INFO     - PAI.paradox.interfaces - Starting BasicMQTTInterface Interface
2022-08-08 17:53:42,474 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT loop started
2022-08-08 17:53:42,491 - INFO     - PAI.paradox.interfaces - Starting HomeAssistantMQTTInterface Interface
2022-08-08 17:53:42,492 - INFO     - PAI - Starting...
2022-08-08 17:53:42,495 - INFO     - PAI.paradox.paradox - Connecting to interface
2022-08-08 17:53:42,497 - INFO     - PAI.paradox.paradox - Using IP Connection
2022-08-08 17:53:42,806 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2022-08-08 17:53:42,855 - INFO     - PAI.paradox.connections.connection - Connection established
2022-08-08 17:53:42,856 - INFO     - PAI.paradox.connections.ip.commands - Authenticating with IP Module
2022-08-08 17:53:42,989 - INFO     - PAI.paradox.connections.ip.commands - Authentication Success. IP(IP100) Module version 101, firmware: 5.20, serial: 7000ee3e
2022-08-08 17:53:43,399 - INFO     - PAI.paradox.connections.ip.commands - Session successfully established with IP Module
2022-08-08 17:53:43,401 - INFO     - PAI.paradox.paradox - Connecting to Panel
2022-08-08 17:53:44,007 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT Broker Connected
2022-08-08 17:53:48,441 - ERROR    - PAI.paradox.paradox - Timeout while connecting to panel. Is an other connection active?
2022-08-08 17:53:48,443 - ERROR    - PAI - Unable to connect to alarm
2022-08-08 17:53:51,448 - INFO     - PAI - Starting...
2022-08-08 17:53:51,448 - INFO     - PAI.paradox.paradox - Disconnecting from the Alarm Panel
2022-08-08 17:53:51,452 - INFO     - PAI.paradox.paradox - Clean Session
2022-08-08 17:53:51,454 - INFO     - PAI.paradox.paradox - Cleaning previous session. Closing connection
2022-08-08 17:53:51,462 - ERROR    - PAI.paradox.connections.protocols - Connection was closed: None
2022-08-08 17:53:51,463 - ERROR    - PAI.paradox.connections.connection - Connection was lost
2022-08-08 17:53:51,468 - INFO     - PAI.paradox.paradox - Disconnected from the Alarm Panel
2022-08-08 17:53:51,469 - INFO     - PAI.paradox.paradox - Connecting to interface
2022-08-08 17:53:51,470 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2022-08-08 17:53:51,565 - INFO     - PAI.paradox.connections.connection - Connection established
2022-08-08 17:53:51,567 - INFO     - PAI.paradox.connections.ip.commands - Authenticating with IP Module
2022-08-08 17:53:51,702 - INFO     - PAI.paradox.connections.ip.commands - Authentication Success. IP(IP100) Module version 101, firmware: 5.20, serial: 7000ee3e
2022-08-08 17:53:52,109 - INFO     - PAI.paradox.connections.ip.commands - Session successfully established with IP Module
2022-08-08 17:53:52,110 - INFO     - PAI.paradox.paradox - Connecting to Panel



Configuration is
LOGGING_LEVEL_CONSOLE: 20
LOGGING_LEVEL_FILE: 40
CONNECTION_TYPE: IP
SERIAL_PORT: /dev/ttyUSB0
SERIAL_BAUD: 57600
IP_CONNECTION_HOST: 192.168.0.180
IP_CONNECTION_PORT: 10000
IP_CONNECTION_PASSWORD: paradox
KEEP_ALIVE_INTERVAL: 10
LIMITS:
  zone: auto
  user: 1-2
  door: ''
  pgm: 1-5
  partition: auto
  module: ''
  repeater: ''
  keypad: ''
  key-switch: ''
SYNC_TIME: true
SYNC_TIME_MIN_DRIFT: 120
PASSWORD: '2580'
MQTT_ENABLE: true
MQTT_HOST: core-mosquitto
MQTT_PORT: 1883
MQTT_KEEPALIVE: 60
MQTT_USERNAME: pai
MQTT_PASSWORD: my secret password
MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE: true
COMMAND_ALIAS:
  arm: partition all arm
  disarm: partition all disarm
MQTT_COMMAND_ALIAS:
  armed_home: arm_stay
  armed_night: arm_sleep
  armed_away: arm
  disarmed: disarm
HOMEASSISTANT_NOTIFICATIONS_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
HOMEASSISTANT_PUBLISH_PARTITION_PROPERTIES:
  - target_state
  - current_state
HOMEASSISTANT_PUBLISH_ZONE_PROPERTIES:
  - open
  - tamper
PUSHBULLET_CONTACTS: []
PUSHBULLET_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
PUSHOVER_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
PUSHOVER_BROADCAST_KEYS: []
SIGNAL_CONTACTS: []
SIGNAL_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
GSM_CONTACTS: []
GSM_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
IP_INTERFACE_ENABLE: false
IP_INTERFACE_PASSWORD: paradox
DUMMY_EVENT_FILTERS: []

**Comment by yozik04** [comment]
@proasnet it is not any way simillar
