### ISSUE TITLE
New firmware

### ISSUE THREAD

**Issue by mm84** [ParadoxAlarmInterface/pai#308]
hi, 
ive question about new firmware. I try to connect but without any success to my EVO panel via IP150+.

Do you know, that my devices (thiers firmwares) are still supported? 

I know that, i cant connect via www. I've
![20220818_081807675_iOS](https://user-images.githubusercontent.com/42741279/185347366-b9b120cd-59ab-47d9-9091-cd1f286bd5a7.png)

**Comment by yozik04** [comment]
Connect from where to where? Is it related to PAI?

**Comment by mm84** [comment]
My whish is connect to evo from ha. I want to arm and disarm from HA, because swan and whole insite gold app is missunderstanding. My HA server and EVO is in the same network. I tried connect via MQTT and PAI integration. Without any success.

**Comment by yozik04** [comment]
Logs or did not happen.

**Comment by mm84** [comment]
2022-08-18 12:16:50,841 - ERROR    - PAI.paradox.connections.protocols - Connection was closed: None
2022-08-18 12:16:50,842 - ERROR    - PAI.paradox.connections.connection - Connection was lost
2022-08-18 12:16:50,843 - INFO     - PAI.paradox.paradox - Disconnected from the Alarm Panel
2022-08-18 12:16:50,844 - INFO     - PAI.paradox.paradox - Connecting to interface
2022-08-18 12:16:50,844 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2022-08-18 12:16:50,849 - INFO     - PAI.paradox.connections.connection - Connection established
2022-08-18 12:16:50,850 - INFO     - PAI.paradox.connections.ip.commands - Authenticating with IP Module
2022-08-18 12:16:50,861 - INFO     - PAI.paradox.connections.ip.commands - Authentication Success. IP(114) Module version 20, firmware: 5.6, serial: 7202f6e4
2022-08-18 12:16:50,883 - INFO     - PAI.paradox.connections.ip.commands - Session successfully established with IP Module
2022-08-18 12:16:50,884 - INFO     - PAI.paradox.paradox - Connecting to Panel
2022-08-18 12:16:50,919 - INFO     - PAI.paradox.paradox - Panel Identified EVO192 version 7.70 build 1
2022-08-18 12:16:50,920 - INFO     - PAI.paradox.paradox - Initiating panel connection
2022-08-18 12:16:50,963 - INFO     - PAI.paradox.hardware.evo.panel - Installer login
2022-08-18 12:16:50,988 - ERROR    - PAI.paradox.paradox - Got ERROR Message: Partition in code lockout (too many bad entries)
2022-08-18 12:16:50,989 - ERROR    - PAI.paradox.lib.handlers - Exception caught during message handling
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout()
paradox.exceptions.CodeLockout
2022-08-18 12:16:50,992 - ERROR    - PAI.paradox.exceptions - Unhandled exception in async loop(<_UnixSelectorEventLoop running=True closed=False debug=False>): 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout()
paradox.exceptions.CodeLockout
Task exception was never retrieved
future: <Task finished name='Task-173' coro=<HandlerRegistry.handle() done, defined at /usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py:101> exception=CodeLockout()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout()
paradox.exceptions.CodeLockout
2022-08-18 12:16:52,008 - ERROR    - PAI.paradox.paradox - Got ERROR Message: Partition in code lockout (too many bad entries)
2022-08-18 12:16:52,012 - ERROR    - PAI.paradox.lib.handlers - Exception caught during message handling
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout()
paradox.exceptions.CodeLockout
2022-08-18 12:16:52,015 - ERROR    - PAI.paradox.exceptions - Unhandled exception in async loop(<_UnixSelectorEventLoop running=True closed=False debug=False>): 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout()
paradox.exceptions.CodeLockout
Task exception was never retrieved
future: <Task finished name='Task-175' coro=<HandlerRegistry.handle() done, defined at /usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py:101> exception=CodeLockout()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout()
paradox.exceptions.CodeLockout
2022-08-18 12:16:53,006 - ERROR    - PAI.paradox.paradox - Got ERROR Message: Partition in code lockout (too many bad entries)
2022-08-18 12:16:53,007 - ERROR    - PAI.paradox.lib.handlers - Exception caught during message handling
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout()
paradox.exceptions.CodeLockout
2022-08-18 12:16:53,008 - ERROR    - PAI.paradox.exceptions - Unhandled exception in async loop(<_UnixSelectorEventLoop running=True closed=False debug=False>): 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout()
paradox.exceptions.CodeLockout
Task exception was never retrieved
future: <Task finished name='Task-177' coro=<HandlerRegistry.handle() done, defined at /usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py:101> exception=CodeLockout()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout()
paradox.exceptions.CodeLockout
2022-08-18 12:16:54,026 - ERROR    - PAI.paradox.paradox - Got ERROR Message: Partition in code lockout (too many bad entries)
2022-08-18 12:16:54,026 - ERROR    - PAI.paradox.lib.handlers - Exception caught during message handling
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout()
paradox.exceptions.CodeLockout
2022-08-18 12:16:54,028 - ERROR    - PAI.paradox.exceptions - Unhandled exception in async loop(<_UnixSelectorEventLoop running=True closed=False debug=False>): 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout()
paradox.exceptions.CodeLockout
Task exception was never retrieved
future: <Task finished name='Task-179' coro=<HandlerRegistry.handle() done, defined at /usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py:101> exception=CodeLockout()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 640, in handle_error_message
    raise CodeLockout()
paradox.exceptions.CodeLockout

**Comment by yozik04** [comment]
And here is the answer:
`Partition in code lockout (too many bad entries)`

Password is wrong.

**Comment by mm84** [comment]
My bad.

Sorry. Everything work! Thanks for this amazing addon!

Best Regards,
Marcin
________________________________
