### ISSUE TITLE
Periodical authentication failure

### ISSUE THREAD

**Issue by donatas-luciunas** [ParadoxAlarmInterface/pai#312]
## Alarm system
SP6000 version 7.14 build 2
Serial 307USB

## Environment
rpi4-64
Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220802.0 - latest

## Git branch
https://github.com/ParadoxAlarmInterface/pai/tree/3.0.1
_Didn't try with **dev** as it takes a day to reproduce_

## Describe the bug
PAI stops every day for ~2 weeks already.
> Authentication Failed. Wrong Password?

## To Reproduce
1. Start add-on
2. Wait
3. See error

## Logs

```
2022-08-29 19:43:32,735 - INFO     - PAI.paradox.paradox - Disconnecting from the Alarm Panel
2022-08-29 19:43:32,736 - INFO     - PAI.paradox.paradox - Clean Session
2022-08-29 19:43:32,736 - INFO     - PAI.paradox.paradox - Connecting to interface
2022-08-29 19:43:32,737 - INFO     - PAI.paradox.connections.serial_connection - Connecting to serial port /dev/ttyUSB0
2022-08-29 19:43:32,747 - INFO     - PAI.paradox.connections.serial_connection - Serial port open
2022-08-29 19:43:32,750 - INFO     - PAI.paradox.paradox - Connecting to Panel
2022-08-29 19:43:32,839 - INFO     - PAI.paradox.paradox - Panel Identified SP6000 version 7.14 build 2
2022-08-29 19:43:32,840 - INFO     - PAI.paradox.paradox - Initiating panel connection
2022-08-29 19:43:36,938 - ERROR    - PAI.paradox.lib.handlers - Already handled
2022-08-29 19:43:36,940 - ERROR    - PAI.paradox.lib.handlers - No handler for message 0
Detail: Container: 
    fields = Container: 
        data = b'\x00\x00\x00\x00\x16\x07\x14\x02\xaa\xaa\x00\x00\x00\x00\x00\x00'... (truncated, total 36)
        value = Container: 
            po = Container: 
                command = 0
                status = Container: 
                    reserved = False
                    alarm_reporting_pending = False
                    Winload_connected = False
                    NeWare_connected = False
            product_id = (enum) SPECTRA_SP6000 22
            firmware = Container: 
                version = 7
                revision = 20
                build = 2
            panel_id = 43690
            transceiver = Container: 
                firmware_build = 0
                family = 0
                firmware_version = 0
                firmware_revision = 0
                noise_floor_level = 0
                status = Container: 
                    noise_floor_high = False
                    constant_carrier = False
                hardware_revision = 0
        offset1 = 0
        offset2 = 36
        length = 36
    checksum = b'\x87' (total 1)
2022-08-29 19:43:36,941 - ERROR    - PAI.paradox.lib.handlers - Already handled
2022-08-29 19:43:36,943 - ERROR    - PAI.paradox.lib.handlers - No handler for message 0
Detail: Container: 
    fields = Container: 
        data = b'\x00\x00\x00\x00\x16\x07\x14\x02\xaa\xaa\x00\x00\x00\x00\x00\x00'... (truncated, total 36)
        value = Container: 
            po = Container: 
                command = 0
                status = Container: 
                    reserved = False
                    alarm_reporting_pending = False
                    Winload_connected = False
                    NeWare_connected = False
            product_id = (enum) SPECTRA_SP6000 22
            firmware = Container: 
                version = 7
                revision = 20
                build = 2
            panel_id = 43690
            transceiver = Container: 
                firmware_build = 0
                family = 0
                firmware_version = 0
                firmware_revision = 0
                noise_floor_level = 0
                status = Container: 
                    noise_floor_high = False
                    constant_carrier = False
                hardware_revision = 0
        offset1 = 0
        offset2 = 36
        length = 36
    checksum = b'\x87' (total 1)
2022-08-29 19:43:36,944 - INFO     - PAI.paradox.hardware.spectra_magellan.panel - Installer login
2022-08-29 19:43:36,949 - ERROR    - PAI.paradox.hardware.spectra_magellan.panel - Authentication Failed. Wrong Password?
2022-08-29 19:43:36,949 - ERROR    - PAI - PAI Critical exception. Stopping PAI
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/main.py", line 81, in run_loop
    if await alarm.full_connect():
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 211, in full_connect
    if not await self.connect():
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 191, in connect
    result = await self.panel.initialize_communication(cfg.PASSWORD)
  File "/usr/local/lib/python3.9/site-packages/paradox/hardware/spectra_magellan/panel.py", line 217, in initialize_communication
    raise AuthenticationFailed("Wrong PASSWORD")
paradox.exceptions.AuthenticationFailed: Wrong PASSWORD
2022-08-29 19:43:36,953 - INFO     - PAI.paradox.paradox - Disconnecting from the Alarm Panel
2022-08-29 19:43:36,953 - INFO     - PAI.paradox.paradox - Clean Session
2022-08-29 19:43:36,954 - INFO     - PAI.paradox.paradox - Cleaning previous session. Closing connection
2022-08-29 19:43:36,956 - ERROR    - PAI.paradox.connections.protocols - Connection was closed: None
2022-08-29 19:43:36,958 - ERROR    - PAI.paradox.connections.serial_connection - Connection to panel was lost
2022-08-29 19:43:37,246 - INFO     - PAI.paradox.paradox - Disconnected from the Alarm Panel
2022-08-29 19:43:37,247 - INFO     - PAI.paradox.interfaces.interface_manager - Stopping all interfaces
2022-08-29 19:43:37,247 - INFO     - PAI.paradox.interfaces.interface_manager - Stopping BasicMQTTInterface
2022-08-29 19:43:37,249 - INFO     - PAI.paradox.interfaces.interface_manager - Stopping HomeAssistantMQTTInterface
2022-08-29 19:43:37,254 - ERROR    - PAI.paradox.interfaces.mqtt.core - MQTT Broker unexpectedly disconnected. Code: None
2022-08-29 19:43:37,256 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT loop stopped
2022-08-29 19:43:37,257 - INFO     - PAI - Good bye!
Attempting to load configuration from /data/options.json
```

**Comment by yozik04** [comment]
Of Wow. Very weird.... Did you updated firmware recently?

**Comment by donatas-luciunas** [comment]
Nope. I updated add-on recently, this error appeared on 2.7.1

**Comment by yozik04** [comment]
Closing as **stale**: this issue has had no activity for more than 18 months and could not be reproduced or progressed with the information available.

This is a housekeeping pass, not a judgement on the merit of the request. If this is still relevant on a current PAI release, please comment and it will be reopened, or start a thread in [Discussions](https://github.com/ParadoxAlarmInterface/pai/discussions).
