### ISSUE TITLE
New Paradox MG5050+

### ISSUE THREAD

**Issue by ewintersa** [ParadoxAlarmInterface/pai#319]
## Alarm system
Magellan MG5050+ (M2)

## Environment
Home Assistant Plugin

## Git branch
Current version: 3.1.0

## Describe the bug
Upgraded my old MG5050 panel to the new MG5050+ (M2) - the one with two serial ports.

## To Reproduce
The plugin does not start up.

## Logs
2022-10-12 16:49:59,735 - INFO     - PAI - Starting...
2022-10-12 16:49:59,736 - INFO     - PAI.paradox.paradox - Disconnecting from the Alarm Panel
2022-10-12 16:49:59,736 - INFO     - PAI.paradox.paradox - Clean Session
2022-10-12 16:49:59,737 - INFO     - PAI.paradox.paradox - Cleaning previous session. Closing connection
2022-10-12 16:49:59,740 - ERROR    - PAI.paradox.connections.protocols - Connection was closed: None
2022-10-12 16:49:59,741 - ERROR    - PAI.paradox.connections.connection - Connection was lost
2022-10-12 16:49:59,744 - INFO     - PAI.paradox.paradox - Disconnected from the Alarm Panel
2022-10-12 16:49:59,747 - INFO     - PAI.paradox.paradox - Connecting to interface
2022-10-12 16:49:59,747 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2022-10-12 16:49:59,755 - INFO     - PAI.paradox.connections.connection - Connection established
2022-10-12 16:49:59,756 - INFO     - PAI.paradox.paradox - Connecting to Panel
2022-10-12 16:49:59,783 - INFO     - PAI.paradox.paradox - Panel Identified MG505+ version 1.20 build 1
2022-10-12 16:49:59,783 - INFO     - PAI.paradox.paradox - Initiating panel connection
2022-10-12 16:49:59,804 - ERROR    - PAI - Restarting
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/main.py", line 81, in run_loop
    if await alarm.full_connect():
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 212, in full_connect
    if not await self.connect():
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 176, in connect
    self.panel = create_panel(
  File "/usr/local/lib/python3.9/site-packages/paradox/hardware/__init__.py", line 44, in create_panel
    raise NotImplementedError(
NotImplementedError: We are not sure what panel you have (product_id: 67).             Please create an issue. Maybe we can help you.

**Comment by ewintersa** [comment]
Looking back now, I think this is rather a request to add support for a board and not a bug.

Apologies.

**Comment by yozik04** [comment]
Try to delete and reinstall the plugin's development version. It might work but no promises. Is this a last firmware version?

**Comment by ewintersa** [comment]
It Works!  This team is the BEST EVER!  Thank you.

I'm using Paradox Alarm Interface 3.2.0-dev

**Comment by yozik04** [comment]
Yeeey!!! Please get back in a couple of days to let me know if it is stable enough to release new stable version and update our compatibility page.

**Comment by ewintersa** [comment]
MG5050+ runs stable - same as the MG5050 before.  The only difference is that I can now use Home Assistant together with Olarm (with the two serial ports on the board).

**Comment by zit501** [comment]
> MG5050+ runs stable - same as the MG5050 before. The only difference is that I can now use Home Assistant together with Olarm (with the two serial ports on the board).

@ewintersa, thank you for confirming that you're able to use HA with PAI concurrently with Olarm. 
So to confirm, there's absolutely no issue with two serial sessions being live at the same time on the MG5050+?
I'm receiving my MG5050+ this week to replace my SP6000. Looking forward to it.

I see that the SP6000+ is also now available, also sporting two serial ports. I chose to rather replace mine with an MG5050+ since my RTX3 is dying.

**Comment by ewintersa** [comment]
The 5050+ runs perfectly on Home Assistant as well as Olarm. All activities are shown on both and instructions from either work.Regards,EduardOn 28 Nov 2022, at 10:34, zit501 ***@***.***> wrote:﻿

MG5050+ runs stable - same as the MG5050 before. The only difference is that I can now use Home Assistant together with Olarm (with the two serial ports on the board).

@ewintersa, thank you for confirming that you're able to use HA with PAI concurrently with Olarm.
So to confirm, there's absolutely no issue with two serial sessions being live at the same time on the MG5050+?
I'm receiving my MG5050+ this week to replace my SP6000. Looking forward to it.
I see that the SP6000+ is also now available, also sporting two serial ports. I chose to rather replace mine with an MG5050+ since my RTX3 is dying.

**Comment by jpieren** [comment]
@ewintersa 
How do you connect to the MG5050+ if I may ask? Seriel/IP150/307b?

**Comment by ewintersa** [comment]
I use a NodeMCU (ESP8266) flashed with ESPLink and connected thrue a level shifter (3.3V vs 12V) to one of the serial ports in the MG5050+.

 

I gave the ESP8266 a fixed IP abd cofigured the PAI addon as follows:



And



 

Note the Sync Time Password must be set in Babyware (I set a virtual COM port on my PC and connect to the same ESP8266 device – you must just stop the PAI addon while you do this).

 

I must admit, it took me hours of playing around before I got it right.  Also, I could never figure out when and why, but sometimes the password must have “a”s for “0”s and other times not...

 

If you try to connect to your MG505+ with wrong login details, it disables connectivety for a while (I cannot remember how long) and then it is quicker to reset and restore from a backup).

 

A BACKUP OF YOUR MG5050+ IS VERY IMPORTANT!!!

 

I hope this helps.
