### ISSUE TITLE
Is there support for MG5050+ ?

### ISSUE THREAD

**Issue by agisofttm** [ParadoxAlarmInterface/pai#333]
I've new installation but company installed MG5050+ instead of MG5050 - the difference is that MG5050+ have two serial ports, which is strange. After installation I receive this in log:

`2022-12-15 18:55:17,953 - INFO     - PAI - Starting Paradox Alarm Interface 3.1.0
2022-12-15 18:55:17,954 - INFO     - PAI - Config loaded from /data/options.json
2022-12-15 18:55:17,954 - INFO     - PAI - Console Log level set to 20
2022-12-15 18:55:18,042 - INFO     - PAI.paradox.interfaces - Starting BasicMQTTInterface Interface
2022-12-15 18:55:18,045 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT loop started
2022-12-15 18:55:18,055 - INFO     - PAI.paradox.interfaces - Starting HomeAssistantMQTTInterface Interface
2022-12-15 18:55:18,055 - INFO     - PAI - Starting...
2022-12-15 18:55:18,057 - INFO     - PAI.paradox.paradox - Connecting to interface
2022-12-15 18:55:18,057 - INFO     - PAI.paradox.paradox - Using IP Connection
2022-12-15 18:55:18,265 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2022-12-15 18:55:18,269 - INFO     - PAI.paradox.connections.connection - Connection established
2022-12-15 18:55:18,269 - INFO     - PAI.paradox.connections.ip.commands - Authenticating with IP Module
2022-12-15 18:55:18,280 - INFO     - PAI.paradox.connections.ip.commands - Authentication Success. IP(114) Module version 20, firmware: 5.5, serial: 72035e1b
2022-12-15 18:55:18,300 - INFO     - PAI.paradox.connections.ip.commands - Session successfully established with IP Module
2022-12-15 18:55:18,301 - INFO     - PAI.paradox.paradox - Connecting to Panel
2022-12-15 18:55:18,340 - INFO     - PAI.paradox.paradox - Panel Identified MG505+ª version 1.11 build -1
2022-12-15 18:55:18,340 - INFO     - PAI.paradox.paradox - Initiating panel connection
2022-12-15 18:55:18,377 - ERROR    - PAI - Restarting
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/main.py", line 81, in run_loop
    if await alarm.full_connect():
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 212, in full_connect
    if not await self.connect():
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 176, in connect
    self.panel = create_panel(
  File "/usr/local/lib/python3.9/site-packages/paradox/hardware/__init__.py", line 44, in create_panel
    raise NotImplementedError(
NotImplementedError: We are not sure what panel you have (product_id: 67).             Please create an issue. Maybe we can help you.`

Thank you for your support ❤️

**Comment by jpbarraca** [comment]
According to the report in #319 , yes it works. Please check it.
