### ISSUE TITLE
NotImplementedError on EVOHD+

### ISSUE THREAD

**Issue by anatom74** [ParadoxAlarmInterface/pai#379]
I'm getting the error when trying to run PAI, so I would need a little help here on proper setup.

`2023-07-31 11:59:22,924 - ERROR    - PAI - Restarting
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/main.py", line 81, in run_loop
    if await alarm.full_connect():
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 212, in full_connect
    if not await self.connect():
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 176, in connect
    self.panel = create_panel(
  File "/usr/local/lib/python3.9/site-packages/paradox/hardware/__init__.py", line 46, in create_panel
    raise NotImplementedError(
NotImplementedError: We are not sure what panel you have (product_id: 8).             Please create an issue. Maybe we can help you.
2023-07-31 11:59:25,930 - ERROR    - PAI.paradox.connections.protocols - Connection was closed: None
2023-07-31 11:59:25,930 - ERROR    - PAI.paradox.connections.connection - Connection was lost
2023-07-31 11:59:26,060 - ERROR    - PAI - Restarting`

**Comment by anatom74** [comment]
It passes identification but fails on authentication (although I have checked it several times)
`2023-08-01 10:11:28,204 - INFO     - PAI.paradox.paradox - Connecting to Panel
2023-08-01 10:11:28,227 - INFO     - PAI.paradox.paradox - Panel Identified EVOHD+   version 1.3 build 1
2023-08-01 10:11:28,227 - INFO     - PAI.paradox.paradox - Initiating panel connection
2023-08-01 10:11:28,254 - INFO     - PAI.paradox.hardware.evo.panel - Installer login
2023-08-01 10:11:28,280 - ERROR    - PAI.paradox.hardware.evo.panel - Authentication Failed
2023-08-01 10:11:28,280 - ERROR    - PAI.paradox.paradox - Failed to connect: Failed to initialize communication
2023-08-01 10:11:28,280 - ERROR    - PAI - Unable to connect to alarm`

**Comment by yozik04** [comment]
Then I need details how you connect.
