### ISSUE TITLE
[Question] permission error log file - docker compose

### ISSUE THREAD

**Issue by mrMiimo** [ParadoxAlarmInterface/pai#384]
## Alarm system
Not connected yet

## Environment
- Raspberry Pi4, the only user on the system is the default "pi" user
- Docker Compose

### Git branch
Dev

## Configuration
```
version: '3'

services:
  pai:
    container_name: pai
    restart: unless-stopped
    image: paradoxalarminterface/pai:dev-latest
    volumes:
      - "~/docker/pai/config:/etc/pai:ro"
      - "~/docker/pai/log:/var/log/pai:rw"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - TZ=EUROPE/Rome
    user: "1000:1000"
#    devices:
    ports:
      - "10000:10000"
```

## Question
I've read the whole wiki, and I'm sure I'm doing something wrong 🤦🏻‍♂️... 
The thing is that I can't run PAI in docker compose, according to the logs it's because of permission problems for log file.
What am I missing?

## Logs (if required)
```
PermissionError: [Errno 13] Permission denied: '/var/log/pai/paradox.log'
Attempting to load configuration from /etc/pai/pai.conf
Traceback (most recent call last):
  File "/usr/local/bin/pai-service", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/paradox/console_scripts/pai_run.py", line 36, in main
    main(args)
  File "/usr/local/lib/python3.9/site-packages/paradox/main.py", line 122, in main
    configure_logger(logger)
  File "/usr/local/lib/python3.9/site-packages/paradox/main.py", line 34, in configure_logger
    logfile_handler = RotatingFileHandler(
  File "/usr/local/lib/python3.9/logging/handlers.py", line 153, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/local/lib/python3.9/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
PermissionError: [Errno 13] Permission denied: '/var/log/pai/paradox.log'
```

**Comment by mrMiimo** [comment]
solved, forgot ` sudo chmod 666 ~/docker/pai/log/paradox.log`
