### ISSUE TITLE
EVO192 7.70 build 1 - Cannot connect

### ISSUE THREAD

**Issue by Onepamopa** [ParadoxAlarmInterface/pai#402]
## Alarm system
EVO192 7.70 build 1 (as detected by PAI)

## Environment
- Home Assistant OS
- Python 3.11.6
- ESP32

## Git branch
Tried both main and dev

## Describe the bug
```
2023-10-27 17:33:15,469 - INFO     - PAI - Starting Paradox Alarm Interface 3.2.1
2023-10-27 17:33:15,469 - INFO     - PAI - Config loaded from /data/options.json
2023-10-27 17:33:15,469 - INFO     - PAI - Console Log level set to 20
2023-10-27 17:33:15,485 - INFO     - PAI.paradox.interfaces - Starting BasicMQTTInterface Interface
2023-10-27 17:33:15,486 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT loop started
2023-10-27 17:33:15,488 - INFO     - PAI.paradox.interfaces - Starting HomeAssistantMQTTInterface Interface
2023-10-27 17:33:15,489 - INFO     - PAI - Starting...
2023-10-27 17:33:15,489 - INFO     - PAI.paradox.paradox - Connecting to interface
2023-10-27 17:33:15,489 - INFO     - PAI.paradox.paradox - Using IP Connection
2023-10-27 17:33:15,538 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2023-10-27 17:33:16,489 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT Broker Connected
2023-10-27 17:33:22,765 - INFO     - PAI.paradox.connections.connection - Connection established
2023-10-27 17:33:22,766 - INFO     - PAI.paradox.paradox - Connecting to Panel
2023-10-27 17:33:22,797 - INFO     - PAI.paradox.paradox - Panel Identified EVO192ª version 7.70 build 1
2023-10-27 17:33:22,797 - INFO     - PAI.paradox.paradox - Initiating panel connection
2023-10-27 17:33:27,804 - ERROR    - PAI.paradox.paradox - Timeout while connecting to panel. Is an other connection active?
2023-10-27 17:33:27,805 - ERROR    - PAI - Unable to connect to alarm
```

## To Reproduce
Connection via ESP32 Serial->TCP (using the provided examples)
Baud rate: 57600 (as set on the panel via BabyWare)
Panel has unlocked serial (I purchased unlock via Insite Gold)

## Logs
From the ESP:
```
[17:48:16][C][stream_server:045]: Stream Server:
[17:48:16][C][stream_server:046]:   Address: esphome-web-c1406c.local:1234
[17:48:24][D][stream_server:081]: New client connected from 192.168.254.44
[17:48:24][D][uart_debug:158]: >>> "r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00r"
[17:48:24][D][uart_debug:158]: <<< "r\xFF\x04\x02\x00\x00\xA1Z\x01\ap\x01\x05\ac\xCA\t\x91\x01\x00\x0F\'\x10 \x101\xFFWEVO192\x00\xA0\xE2"
[17:48:24][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:25][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:26][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:27][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:28][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:32][D][stream_server:163]: Client 192.168.254.44 disconnected
[17:48:32][D][stream_server:081]: New client connected from 192.168.254.44
[17:48:32][D][uart_debug:158]: >>> "p%\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x95r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00r"
[17:48:32][D][uart_debug:158]: <<< "r\xFF\x04\x02\x00\x00\xA1Z\x01\ap\x01\x05\ac\xCA\t\x91\x01\x00\x0F\'\x10 \x101\xFFWEVO192\x00\xA0\xE2"
[17:48:32][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:33][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:34][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:35][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:36][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:37][D][stream_server:163]: Client 192.168.254.44 disconnected
[17:48:37][D][stream_server:081]: New client connected from 192.168.254.44
[17:48:37][D][uart_debug:158]: >>> "p%\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x95r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00r"
[17:48:37][D][uart_debug:158]: <<< "r\xFF\x04\x02\x00\x00\xA1Z\x01\ap\x01\x05\ac\xCA\t\x91\x01\x00\x0F\'\x10 \x101\xFFWEVO192\x00\xA0\xE2"
[17:48:37][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:39][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:39][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:40][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:41][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:43][D][stream_server:081]: New client connected from 192.168.254.44
[17:48:43][D][stream_server:163]: Client 192.168.254.44 disconnected
[17:48:44][D][uart_debug:158]: >>> "p%\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x95r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00r"
[17:48:45][D][uart_debug:158]: >>> "r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00r"
[17:48:45][D][uart_debug:158]: <<< "r\xFF\x04\x02\x00\x00\xA1Z\x01\ap\x01\x05\ac\xCA\t\x91\x01\x00\x0F\'\x10 \x101\xFFWEVO192\x00\xA0\xE2"
[17:48:45][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:46][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:47][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:48][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[17:48:49][D][sensor:094]: 'Uptime Sensor': Sending state 118.62400 s with 0 decimals of accuracy
[17:48:49][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
```

**Comment by lpaolini** [comment]
This firmware version is not supported, as the serial communication is encrypted, see here: #335.
You have to use the Paradox network adapter IP150.

**Comment by Onepamopa** [comment]
@lpaolini the serial communication is encrypted until you purchase an unlock code.
I have purchased an unlock code, but I think I forgot to add it. I'm researching on how to do that at the moment, and will provide more information when I'm done. From what I remember the code could only be entered via TM50/TM70 keypad (of which I have both).

**Comment by lpaolini** [comment]
@Onepamopa Ha, interesting. How much does it cost?

**Comment by Onepamopa** [comment]
It costs 6$ per panel, code is provided in the invoice and in insite gold (installer), on the invoice the instructions say:
To unlock, enter the code in section [3000] EVO or [300] MGSP, in installer programing mode, using a TM70/50 keypad.

It requires babyware/insite gold be disconnected, all areas - disarmed - then you enter the installer code on the keypad and so forth.

Since I'm my own "installer" i just purchased for myself, but you can purchase from your security company/installer.

I'll test connectivity ESP32 <-> PAI a bit later, and report back.

**Comment by yozik04** [comment]
Interesting 🍿
If it works then we need to update our documentation.

**Comment by Onepamopa** [comment]
Unfortunately I fried my ESP32 and don't have a replacement.
Got a few 8266s but no idea if it'd work with them...

**Comment by lpaolini** [comment]
So it's just a tax for keeping on using the serial port...
I wonder if the end user can purchase one or if it's just for installers.

**Comment by Onepamopa** [comment]
@lpaolini I'm not an official installer by any means. I just purchased everything I needed, assembled, installed, programmed it myself. In essence - I'm my own installer :)

**Comment by Onepamopa** [comment]
Okay so.... getting "Invalid PC password" - I doublechecked via the TM70 - Panel id is 0001, PC password is 4 digits. I'm setting the correct password, but getting:
```
2023-10-27 19:40:29,591 - INFO     - PAI.paradox.interfaces - Starting BasicMQTTInterface Interface
2023-10-27 19:40:29,592 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT loop started
2023-10-27 19:40:29,594 - INFO     - PAI.paradox.interfaces - Starting HomeAssistantMQTTInterface Interface
2023-10-27 19:40:29,594 - INFO     - PAI - Starting...
2023-10-27 19:40:29,594 - INFO     - PAI.paradox.paradox - Connecting to interface
2023-10-27 19:40:29,594 - INFO     - PAI.paradox.paradox - Using IP Connection
2023-10-27 19:40:29,641 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2023-10-27 19:40:29,643 - INFO     - PAI.paradox.connections.connection - Connection established
2023-10-27 19:40:29,643 - INFO     - PAI.paradox.paradox - Connecting to Panel
2023-10-27 19:40:29,823 - INFO     - PAI.paradox.paradox - Panel Identified EVO192 version 7.70 build 1
2023-10-27 19:40:29,823 - INFO     - PAI.paradox.paradox - Initiating panel connection
2023-10-27 19:40:30,064 - INFO     - PAI.paradox.hardware.evo.panel - Installer login
2023-10-27 19:40:30,573 - ERROR    - PAI.paradox.paradox - Got ERROR Message: Invalid PC Password
2023-10-27 19:40:30,574 - ERROR    - PAI.paradox.lib.handlers - Exception caught during message handling
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 649, in handle_error_message
    raise AuthenticationFailed()
paradox.exceptions.AuthenticationFailed
2023-10-27 19:40:30,574 - ERROR    - PAI.paradox.exceptions - Unhandled exception in async loop(<_UnixSelectorEventLoop running=True closed=False debug=False>): 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 649, in handle_error_message
    raise AuthenticationFailed()
paradox.exceptions.AuthenticationFailed
Task exception was never retrieved
future: <Task finished name='Task-13' coro=<HandlerRegistry.handle() done, defined at /usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py:101> exception=AuthenticationFailed()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 649, in handle_error_message
    raise AuthenticationFailed()
paradox.exceptions.AuthenticationFailed
2023-10-27 19:40:30,597 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT Broker Connected
2023-10-27 19:40:31,623 - ERROR    - PAI.paradox.paradox - Got ERROR Message: Invalid PC Password
2023-10-27 19:40:31,623 - ERROR    - PAI.paradox.lib.handlers - Exception caught during message handling
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 649, in handle_error_message
    raise AuthenticationFailed()
paradox.exceptions.AuthenticationFailed
2023-10-27 19:40:31,623 - ERROR    - PAI.paradox.exceptions - Unhandled exception in async loop(<_UnixSelectorEventLoop running=True closed=False debug=False>): 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 112, in handle
    await handler(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py", line 61, in __call__
    result = self._handle(data)
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 649, in handle_error_message
    raise AuthenticationFailed()
paradox.exceptions.AuthenticationFailed
Task exception was never retrieved
future: <Task finished name='Task-15' coro=<HandlerRegistry.handle() done, defined at /usr/local/lib/python3.9/site-packages/paradox/lib/handlers.py:101> exception=AuthenticationFailed()>
```

**Comment by Onepamopa** [comment]
Here's what I get from esphome debug:
```
[19:46:47][D][uart_debug:158]: <<< "\xE0\xFF\x00L\x14\x17\n"
[19:46:47][D][uart_debug:158]: <<< "\e\x130\x01\x01\x03\x00\x00\x00\x00\x00\x02PIR KORIDOR     \x00\x8A"
[19:46:47][D][uart_debug:158]: <<< "\xE0\xFF\x00M\x14\x17\n"
[19:46:47][D][uart_debug:158]: <<< "\e\x131\x00\x01\x03\x00\x00\x00\x00\x00\x02PIR KORIDOR     \x00\x8B"
[19:46:49][D][stream_server:081]: New client connected from 192.168.254.44
[19:46:49][D][uart_debug:158]: >>> "r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00r"
[19:46:50][D][uart_debug:158]: <<< "r\xFF\x04\x02\x00\x00\xA1Z\x01\ap\x01\x05\ac\xCA\t\x91\x01\x00\x0F\'\x10 \x101\xFFWEVO192\x00\x00B"
[19:46:50][D][uart_debug:158]: >>> "_ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x81"
[19:46:50][D][uart_debug:158]: <<< "\x00\x00\x00\x00\x05\ap\x00\x00\x01\x00\x00\b0\x02\x01\x00\x05\ac\xCA\x04\x0F\x0FSP\xC0\x00\x00\x00\x00\x00\x00\x00\x00\x00v"
[19:46:50][D][uart_debug:158]: >>> "\x00\x00\x00\x00\x05\ap\x00\x00\x01\x00\x00\b0\x02\x01\x00\x05\ac\xCA\x04\x0F\x0FSP\xC0\x00\x00\x00\x00\x00\x00\x00\x00\x00v"
[19:46:50][D][uart_debug:158]: <<< "p\x04\x12\x86"
[19:46:51][D][uart_debug:158]: >>> "\x00\x00\x00\x00\x05\ap\x00\x00\x01\x00\x00\b0\x02\x01\x00\x05\ac\xCA\x04\x0F\x0FSP\xC0\x00\x00\x00\x00\x00\x00\x00\x00\x00v"
[19:46:51][D][uart_debug:158]: <<< "p\x04\x12\x86"
[19:46:52][D][uart_debug:158]: >>> "\x00\x00\x00\x00\x05\ap\x00\x00\x01\x00\x00\b0\x02\x01\x00\x05\ac\xCA\x04\x0F\x0FSP\xC0\x00\x00\x00\x00\x00\x00\x00\x00\x00v"
[19:46:52][D][uart_debug:158]: <<< "p\x04\x12\x86"
[19:46:53][D][uart_debug:158]: >>> "\x00\x00\x00\x00\x05\ap\x00\x00\x01\x00\x00\b0\x02\x01\x00\x05\ac\xCA\x04\x0F\x0FSP\xC0\x00\x00\x00\x00\x00\x00\x00\x00\x00v"
[19:46:53][D][uart_debug:158]: <<< "p\x04\x12\x86"
[19:46:54][D][uart_debug:158]: >>> "\x00\x00\x00\x00\x05\ap\x00\x00\x01\x00\x00\b0\x02\x01\x00\x05\ac\xCA\x04\x0F\x0FSP\xC0\x00\x00\x00\x00\x00\x00\x00\x00\x00v"
[19:46:54][D][uart_debug:158]: <<< "p\x04\x12\x86"
[19:46:57][D][uart_debug:158]: >>> "p\x04\x05y"
[19:46:57][D][stream_server:163]: Client 192.168.254.44 disconnected
[19:46:57][D][uart_debug:158]: <<< "p\x04\x10\x84"
```

**Comment by Onepamopa** [comment]
My bad.. it connected.
I forgot to change the password in the 3rd location :) there's 3 places where a password can be set.. So the password after "SYNC_TIME" is the one used.

```
2023-10-27 19:50:23,404 - INFO     - PAI - Starting Paradox Alarm Interface 3.3.0-dev
2023-10-27 19:50:23,404 - INFO     - PAI - Config loaded from /data/options.json
2023-10-27 19:50:23,404 - INFO     - PAI - Console Log level set to 20
2023-10-27 19:50:23,422 - INFO     - PAI.paradox.interfaces - Starting BasicMQTTInterface Interface
2023-10-27 19:50:23,423 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT loop started
2023-10-27 19:50:23,425 - INFO     - PAI.paradox.interfaces - Starting HomeAssistantMQTTInterface Interface
2023-10-27 19:50:23,425 - INFO     - PAI - Starting...
2023-10-27 19:50:23,425 - INFO     - PAI.paradox.paradox - Connecting to interface
2023-10-27 19:50:23,425 - INFO     - PAI.paradox.paradox - Using IP Connection
2023-10-27 19:50:23,473 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2023-10-27 19:50:23,476 - INFO     - PAI.paradox.connections.connection - Connection established
2023-10-27 19:50:23,476 - INFO     - PAI.paradox.paradox - Connecting to Panel
2023-10-27 19:50:23,732 - INFO     - PAI.paradox.paradox - Panel Identified EVO192 version 7.70 build 1
2023-10-27 19:50:23,732 - INFO     - PAI.paradox.paradox - Initiating panel connection
2023-10-27 19:50:23,952 - INFO     - PAI.paradox.hardware.evo.panel - Installer login
2023-10-27 19:50:24,006 - INFO     - PAI.paradox.hardware.evo.panel - Authentication Success
2023-10-27 19:50:24,006 - INFO     - PAI.paradox.paradox - Connection OK
2023-10-27 19:50:24,006 - INFO     - PAI.paradox.paradox - Loading data from panel memory
2023-10-27 19:50:24,006 - INFO     - PAI.paradox.hardware.panel - Loading definitions
2023-10-27 19:50:24,006 - INFO     - PAI.paradox.hardware.panel - Updating Definitions from Panel
2023-10-27 19:50:24,425 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT Broker Connected
2023-10-27 19:50:25,528 - INFO     - PAI.paradox.hardware.panel - Zone definitions loaded (1.52s)
2023-10-27 19:50:25,585 - INFO     - PAI.paradox.hardware.panel - Partition definitions loaded (0.06s)
```

**Comment by Onepamopa** [comment]
Now if I can only figure out how to make babyware connect via port 10000 on PAI@HA ... would be perfect

**Comment by Onepamopa** [comment]
Also.... I'm not seeing PAI/paradox in HA.. the addon is installed / running, but ... no entities, etc?

**Comment by Onepamopa** [comment]
@lpaolini is there a way to connect the ESP to IP150's "PCS" serial port (to only receive events), or directly to the serial port to only receive (not transmit) ?

**Comment by lpaolini** [comment]
@Onepamopa I've just learned the PCS port is for connecting a PCS250 GPRS/GSM Communicator Module, which normally connects to the serial port of the panel, when it's not used by the IP150.
Unfortunately I don't have a cable with a suitable connector to plug into that port and make some tests, but I've opened the IP150 to check the wiring and the RX/TX signals are not directly connected between the two ports.
So, I'm not sure, but I would expect the PCS port to mirror the PANEL port both ways.

**Comment by yozik04** [comment]
> @lpaolini is there a way to connect the ESP to IP150's "PCS" serial port (to only receive events), or directly to the serial port to only receive (not transmit) ?

There was a feature request when PAI acts passively. But I did not implement it.

**Comment by lpaolini** [comment]
@Onepamopa I can't find any trace of that unlock code on any website.
Could you please tell us the product code or how it is called in your invoice?
Thanks.

**Comment by Onepamopa** [comment]
@lpaolini You need to use the Insite Gold app + IP150 (or any other method of remote connection between swan & your panel).

**Comment by Onepamopa** [comment]
As for PCS .. I'll purchase a cable for IP150 -> PCS @ monday and will try connecting the ESP there.

**Comment by Onepamopa** [comment]
@yozik04 yozik04
> There was a feature request when PAI acts passively. But I did not implement it.

If you've got some time, add that to the dev branch? I'll gladly test.

**Comment by yozik04** [comment]
It is probably not that simple. Where to get available zone data, partitions and so on... Currently we just read it out from the memory after the connection.

**Comment by Onepamopa** [comment]
@yozik04 I tried connecting IP150 & the esp to the same serial port, but when PAI connects, the IP module goes "missing".
Ideally I'd like to keep it because it's useful.. 

I have 3 options:
1. Buy a IP150->PCS cable @ monday and try connecting the ESP there.
2. Buy BUS2SER and connect there
3. Buy EVOHD+ which has 2 serial ports (no idea if they can be used at the same time) - considering the price of BUS2SER is almost comparable to EVOHD+, if all else fails, EVOHD+ could be the better option (if both serial ports can be used at the same time) because I'd be able to resell EVO192 and get at least some of the $ back.

Will see @ monday..

**Comment by lpaolini** [comment]
Reading from EVOHD+ documentation, it looks like a few more keyboards can be used as well for entering the unlock code.

<img width="286" alt="Screenshot 2023-10-29 at 20 40 14" src="https://github.com/ParadoxAlarmInterface/pai/assets/377807/5ae46fb7-98ae-4a53-a66a-b709c8886a80">

**Comment by lpaolini** [comment]
@Onepamopa I don't have a Paradox account for logging into Insite Gold and request an unlock code.
Is [http://www.paradoxmyhome.com/](http://www.paradoxmyhome.com/) the right place to create one?
I tried, but without success (the account doesn't appear to be active).

**Comment by Onepamopa** [comment]
@lpaolini It's been years since I created my account, I don't remember exactly where - website or the app directly..
Try to reach out to your installer, or perhaps write to support@paradox.com ... idk..

**Comment by lpaolini** [comment]
Ok, thanks. The problem is that I'm my own installer too.
I'll try to contact a reseller, but I'm not very optimistic about it. I'll let you know how it goes...

**Comment by Onepamopa** [comment]
@lpaolini https://www.paradox.com/SPMH-G2K_rev00.pdf

**Comment by Onepamopa** [comment]
Got the IP150->PCS cable, will test tomorrow.. hopefully it'd work..

**Comment by Onepamopa** [comment]
Well, all I can say is - success! Connecting PAI ESP8266 <-> IP150 <-> Panel -- works like a charm.
I think there's something about the arming that's wrong (for example - I arm via PAI - it arms as "Stay" not "Arm" but that's details to be worked out :)

**Comment by Onepamopa** [comment]
@lpaolini if you're unable to get a code - let me know, I'll purchase one for you :)

**Comment by salphire3** [comment]
> [@lpaolini](https://github.com/lpaolini) if you're unable to get a code - let me know, I'll purchase one for you :)

Hi. Sorry for reviving an old thread. I have an sp6000+ with a locked serial port. Do you think you can provide the unlock code?

**Comment by Onepamopa** [comment]
Call your installer, the unlock code is ~5$ or something like that.

**Comment by salphire3** [comment]
No prob. Already contacted. Hope to get the code soon. The panel is identified using the esp32. But got the error of 'other connection' which probably mean locked serial port

**Comment by yozik04** [comment]
Closing: Reporter marked this as *solved* in the title. Thanks for reporting back.

**Comment by yozik04** [comment]
Closing: Reporter marked this as *solved* in the title. Thanks for reporting back.
