### ISSUE TITLE
NotImplementedError on SP7000+

### ISSUE THREAD

**Issue by selmirsoftic** [ParadoxAlarmInterface/pai#403]
I'm getting the error when trying to run PAI:

2023-10-31 21:28:26,270 - INFO     - PAI - Starting Paradox Alarm Interface 3.2.1
2023-10-31 21:28:26,270 - INFO     - PAI - Config loaded from /data/options.json
2023-10-31 21:28:26,270 - INFO     - PAI - Console Log level set to 20
2023-10-31 21:28:26,293 - INFO     - PAI.paradox.interfaces - Starting BasicMQTTInterface Interface
2023-10-31 21:28:26,294 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT loop started
2023-10-31 21:28:26,296 - INFO     - PAI.paradox.interfaces - Starting HomeAssistantMQTTInterface Interface
2023-10-31 21:28:26,296 - INFO     - PAI - Starting...
2023-10-31 21:28:26,297 - INFO     - PAI.paradox.paradox - Connecting to interface
2023-10-31 21:28:26,297 - INFO     - PAI.paradox.paradox - Using IP Connection
2023-10-31 21:28:26,358 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2023-10-31 21:28:26,360 - INFO     - PAI.paradox.connections.connection - Connection established
2023-10-31 21:28:26,360 - INFO     - PAI.paradox.connections.ip.commands - Authenticating with IP Module
2023-10-31 21:28:26,366 - INFO     - PAI.paradox.connections.ip.commands - Authentication Success. IP(114) Module version 20, firmware: 5.6, serial: 7204cd73
2023-10-31 21:28:26,378 - INFO     - PAI.paradox.connections.ip.commands - Session successfully established with IP Module
2023-10-31 21:28:26,378 - INFO     - PAI.paradox.paradox - Connecting to Panel
2023-10-31 21:28:26,402 - INFO     - PAI.paradox.paradox - Panel Identified SP700+  version 1.21 build 3
2023-10-31 21:28:26,402 - INFO     - PAI.paradox.paradox - Initiating panel connection
2023-10-31 21:28:26,425 - ERROR    - PAI - Restarting
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/main.py", line 81, in run_loop
    if await alarm.full_connect():
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 212, in full_connect
    if not await self.connect():
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 176, in connect
    self.panel = create_panel(
  File "/usr/local/lib/python3.9/site-packages/paradox/hardware/__init__.py", line 46, in create_panel
    raise NotImplementedError(
NotImplementedError: We are not sure what panel you have (product_id: 30).             Please create an issue. Maybe we can help you.
2023-10-31 21:28:27,305 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT Broker Connected

any suggestion? tnx

**Comment by yozik04** [comment]
Fixed in #408
