### ISSUE TITLE
Support for SP550+ (product id: 28)

### ISSUE THREAD

**Issue by bocsitomcsi** [ParadoxAlarmInterface/pai#413]
## Alarm system
Panel model: SP550+  version 1.28 build 1
Access mode: IP(114) Module version 20, firmware: 5.6, serial: 720586e9

## Environment
- Raspberrypi, debian
- Containerized solution

## Git branch
Tried out version 3.2.1, 3.3.0 and lates-dev one as well. Sympton is the same.

## Describe the bug
As part of the initialization process it failes with below mentioned problem.

## To Reproduce
Start container (docker-compose up).

## Logs
As this part does not contain any sensitive information I would add here the log:

```
paradox    | 2023-11-24 19:43:47,164 - INFO     - PAI - Starting Paradox Alarm Interface 3.3.0-dev
paradox    | 2023-11-24 19:43:47,165 - INFO     - PAI - Config loaded from /etc/pai/pai.conf
paradox    | 2023-11-24 19:43:47,165 - INFO     - PAI - Console Log level set to 20
paradox    | 2023-11-24 19:43:47,252 - INFO     - PAI.paradox.interfaces - Starting BasicMQTTInterface Interface
paradox    | 2023-11-24 19:43:47,255 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT loop started
paradox    | 2023-11-24 19:43:47,265 - INFO     - PAI.paradox.interfaces - Starting HomeAssistantMQTTInterface Interface
paradox    | 2023-11-24 19:43:47,266 - INFO     - PAI - Starting...
paradox    | 2023-11-24 19:43:47,267 - INFO     - PAI.paradox.paradox - Connecting to interface
paradox    | 2023-11-24 19:43:47,267 - INFO     - PAI.paradox.paradox - Using IP Connection
paradox    | 2023-11-24 19:43:47,526 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
paradox    | 2023-11-24 19:43:47,531 - INFO     - PAI.paradox.connections.connection - Connection established
paradox    | 2023-11-24 19:43:47,532 - INFO     - PAI.paradox.connections.ip.commands - Authenticating with IP Module
paradox    | 2023-11-24 19:43:47,539 - INFO     - PAI.paradox.connections.ip.commands - Authentication Success. IP(114) Module version 20, firmware: 5.6, serial: 720586e9
paradox    | 2023-11-24 19:43:47,558 - INFO     - PAI.paradox.connections.ip.commands - Session successfully established with IP Module
paradox    | 2023-11-24 19:43:47,559 - INFO     - PAI.paradox.paradox - Connecting to Panel
paradox    | 2023-11-24 19:43:47,592 - INFO     - PAI.paradox.paradox - Panel Identified SP550+  version 1.28 build 1
paradox    | 2023-11-24 19:43:47,593 - INFO     - PAI.paradox.paradox - Initiating panel connection
paradox    | 2023-11-24 19:43:47,621 - ERROR    - PAI - Restarting
paradox    | Traceback (most recent call last):
paradox    |   File "/usr/local/lib/python3.9/site-packages/paradox/main.py", line 81, in run_loop
paradox    |     if await alarm.full_connect():
paradox    |   File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 212, in full_connect
paradox    |     if not await self.connect():
paradox    |   File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 176, in connect
paradox    |     self.panel = create_panel(
paradox    |   File "/usr/local/lib/python3.9/site-packages/paradox/hardware/__init__.py", line 47, in create_panel
paradox    |     raise NotImplementedError(
paradox    | NotImplementedError: We are not sure what panel you have (product_id: 28).             Please create an issue. Maybe we can help you.

```

**Comment by yozik04** [comment]
I see Paradox has started to use GPT-4 to generate new panels. :)

**Comment by bocsitomcsi** [comment]
Maybe I am wrong but SP550+ shouldn't be rather SP5500+? Or are these ones are different?

**Comment by bocsitomcsi** [comment]
I can confirm it is working as expected. Thanks for the quick help.
