### ISSUE TITLE
MG5050 on OpenHAB - is it supported?

### ISSUE THREAD

**Issue by captain1019** [ParadoxAlarmInterface/pai#438]
## Alarm system

MG5050
IP150 module
## Environment

Ubuntu 22.04 with OpenHAB
## Question

Im in the process of migrating from Home assistant to OpenHAB.  I tried to use the Official Paradox Binding, but seeing that the Binding only supports EVO models im a bit stumped and dont know what to do.
I also tried to add it anyway and im getting the below error:
```
org.openhab.binding.paradoxalarm.internal.exceptions.ParadoxRuntimeException: Unsupported panel type: MG5050
	at org.openhab.binding.paradoxalarm.internal.communication.ParadoxBuilderFactory.createBuilder(ParadoxBuilderFactory.java:40) ~[?:?]
	at org.openhab.binding.paradoxalarm.internal.handlers.ParadoxIP150BridgeHandler.createDiscoveredCommunicatorJob(ParadoxIP150BridgeHandler.java:167) ~[?:?]
	at org.openhab.binding.paradoxalarm.internal.handlers.ParadoxIP150BridgeHandler.lambda$1(ParadoxIP150BridgeHandler.java:110) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

As you can see it says "Unsupported panel type: MG5050"

Is this binding maintained by this community by any chance?  I would really appreciate it if support could be added for MG5050.

If not, is it still possible to get the MG5050 working nevetheless?  Im a bit new to this all.
I saw this documentation https://github.com/ParadoxAlarmInterface/pai/wiki/OpenHAB
Does this setup work for MG5050?  If yes, how do i bind the Bridge manually in `things/broker.things` if i use MQTT Broker via the UI in OpenHAB?  I heard that you cant mix the 2 UI and manually coding it.

Thanks in advance

**Comment by yozik04** [comment]
You asked a question in the wrong repository. This repo uses MQTT to speak with home automation systems. Your question is regarding some Java version of the Integration which I do not know about.

**Comment by captain1019** [comment]
> You asked a question in the wrong repository. This repo uses MQTT to speak with home automation systems. Your question is regarding some Java version of the Integration which I do not know about.

My question was a 2 part question.
If the integration is not supported directly from this repo, then i asked:


> If not, is it still possible to get the MG5050 working nevetheless? Im a bit new to this all.
> I saw this documentation https://github.com/ParadoxAlarmInterface/pai/wiki/OpenHAB
> Does this setup work for MG5050? If yes, how do i bind the Bridge manually in `things/broker.things` if i use MQTT Broker via the UI in OpenHAB? I heard that you cant mix the 2 UI and manually coding it.

Id appreciate if you can assist me with this, since the community seems quite dead on gitter and im unable to get any community support elsewhere.

**Comment by yozik04** [comment]
Instead of the integration you installed into OpenHAB you could use our project that would send events to MQTT. OpenHAB would then listen to these events and react. If I remember correctly OpenHAB, has some auto discovery of HomeAssistant's MQTT discovery format. If not, then you will still be able to configure all the bindings manually.
