### ISSUE TITLE
IO_TIMEOUT not visible in HA web interface

### ISSUE THREAD

**Issue by martinl** [ParadoxAlarmInterface/pai#478]
## Alarm system
EVO192, access mode IP150, latest firmware, using site id and email to connect

## Environment
Home Assistant

## Git branch
3.5.0 release (no difference to dev branch in relation to IO_TIMEOUT)

## Describe the bug
IO_TIMEOUT option is not visible in Home Assistant web interface. 
I tried to increase IO_TIMEOUT to 10 in HA OS default pai.conf and used yaml to add it in HA web interface. It had no effect - still getting panel send/receive timeout in 1.0 sec in logs.

## To Reproduce
open PAI config in HA web interface

## Logs
```
2024-06-29 17:10:18,489 - INFO     - MainThread - PAI.paradox.paradox - Connecting to interface
2024-06-29 17:10:18,489 - INFO     - MainThread - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2024-06-29 17:10:18,490 - DEBUG    - MainThread - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/interface/pai_status=initializing
2024-06-29 17:10:18,490 - DEBUG    - MainThread - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/interface/availability=offline
2024-06-29 17:10:18,491 - INFO     - MainThread - PAI.paradox.connections.connection - Connection established
2024-06-29 17:10:18,491 - INFO     - MainThread - PAI.paradox.interfaces.ip_interface.interface - Client 15 connected
2024-06-29 17:10:18,491 - INFO     - MainThread - PAI.paradox.paradox - Pausing PAI
2024-06-29 17:10:18,491 - INFO     - MainThread - PAI.paradox.connections.ip.commands - Authenticating with IP Module
2024-06-29 17:10:18,492 - INFO     - MainThread - PAI.paradox.interfaces.ip_interface.client_connection - Authenticating to IP interface
2024-06-29 17:10:18,492 - INFO     - MainThread - PAI.paradox.interfaces.ip_interface.client_connection - Authentication Success
2024-06-29 17:10:18,493 - INFO     - MainThread - PAI.paradox.connections.ip.commands - Authentication Success. IP(IP150) Module version 20, firmware: 1.32, serial: 71234567
2024-06-29 17:10:18,493 - DEBUG    - MainThread - PAI.paradox.connections.ip.commands - Sending keep alive request
2024-06-29 17:10:18,494 - DEBUG    - MainThread - PAI.paradox.connections.ip.commands - Keep alive response: b'00'
2024-06-29 17:10:18,495 - DEBUG    - MainThread - PAI.paradox.connections.ip.commands - Sending upload download connection request
2024-06-29 17:10:18,496 - DEBUG    - MainThread - PAI.paradox.connections.ip.commands - Upload download connection response: b'0100000000000000000000000000000000'
2024-06-29 17:10:18,496 - DEBUG    - MainThread - PAI.paradox.connections.ip.commands - Sending toggle keep alive request
2024-06-29 17:10:18,498 - DEBUG    - MainThread - PAI.paradox.connections.ip.commands - Toggle keep alive response: b'01'
2024-06-29 17:10:18,498 - INFO     - MainThread - PAI.paradox.connections.ip.commands - Session successfully established with IP Module
2024-06-29 17:10:18,498 - INFO     - MainThread - PAI.paradox.paradox - Connecting to Panel
2024-06-29 17:10:19,500 - DEBUG    - MainThread - PAI.paradox.paradox - send/receive timeout in 1.0021 s
2024-06-29 17:10:19,500 - DEBUG    - MainThread - PAI.paradox.paradox - Request retry (attempt 2/5)
2024-06-29 17:10:20,503 - DEBUG    - MainThread - PAI.paradox.paradox - send/receive timeout in 1.0016 s
2024-06-29 17:10:20,503 - DEBUG    - MainThread - PAI.paradox.paradox - Request retry (attempt 3/5)
2024-06-29 17:10:21,505 - DEBUG    - MainThread - PAI.paradox.paradox - send/receive timeout in 1.0016 s
2024-06-29 17:10:21,505 - DEBUG    - MainThread - PAI.paradox.paradox - Request retry (attempt 4/5)
2024-06-29 17:10:22,508 - DEBUG    - MainThread - PAI.paradox.paradox - send/receive timeout in 1.0016 s
2024-06-29 17:10:22,508 - DEBUG    - MainThread - PAI.paradox.paradox - Request retry (attempt 5/5)
2024-06-29 17:10:23,510 - DEBUG    - MainThread - PAI.paradox.paradox - send/receive timeout in 1.0016 s
2024-06-29 17:10:23,510 - ERROR    - MainThread - PAI.paradox.paradox - Timeout while connecting to panel. Is an other connection active?
2024-06-29 17:10:23,510 - ERROR    - MainThread - PAI - Unable to connect to alarm
2024-06-29 17:10:23,511 - DEBUG    - MainThread - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/interface/pai_status=error
2024-06-29 17:10:23,511 - DEBUG    - MainThread - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/interface/availability=offline
2024-06-29 17:10:27,013 - INFO     - MainThread - PAI - Captured signal SIGTERM. Exiting
2024-06-29 17:10:27,013 - INFO     - MainThread - PAI.paradox.paradox - Disconnecting from the Alarm Panel
2024-06-29 17:10:27,013 - INFO     - MainThread - PAI.paradox.paradox - Clean Session
2024-06-29 17:10:27,014 - INFO     - MainThread - PAI.paradox.paradox - Cleaning previous session. Closing connection
2024-06-29 17:10:27,014 - ERROR    - MainThread - PAI.paradox.connections.protocols - Connection was closed: None
2024-06-29 17:10:27,014 - ERROR    - MainThread - PAI.paradox.connections.connection - Connection was lost
2024-06-29 17:10:27,015 - ERROR    - MainThread - PAI.paradox.interfaces.ip_interface.interface - Client 15 connection raised exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/paradox/interfaces/ip_interface/interface.py", line 77, in handle_client
    await connection.handle()
  File "/usr/local/lib/python3.11/site-packages/paradox/interfaces/ip_interface/client_connection.py", line 135, in handle
    await self._handle_passthrough(in_message)
  File "/usr/local/lib/python3.11/site-packages/paradox/interfaces/ip_interface/client_connection.py", line 171, in _handle_passthrough
    self.alarm.connection.write(in_message.payload)
  File "/usr/local/lib/python3.11/site-packages/paradox/connections/connection.py", line 49, in write
    raise ConnectionError("Not connected")
ConnectionError: Not connected
2024-06-29 17:10:27,016 - INFO     - MainThread - PAI.paradox.interfaces.ip_interface.interface - Client 15 disconnected
2024-06-29 17:10:27,016 - DEBUG    - MainThread - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/interface/pai_status=stopped
2024-06-29 17:10:27,016 - DEBUG    - MainThread - PAI.paradox.interfaces.mqtt.core - MQTT: paradox/interface/availability=offline
```

**Comment by yozik04** [comment]
IO_TIMEOUT won't help you in this case. Provide more info.

**Comment by martinl** [comment]
EVO192 has fw 07.70.1 and ip150mq has 6.15. Via BlueEye installer menu works with same credentials (site id, panel s/n and pc installer pin). Home Assistant is also current latest version. One thing I noticed that if I also include e-mail in site credentials then I get panel not found error in logs. Maybe that helps.

**Comment by yozik04** [comment]
Mq is MQTT version. I have no idea if that works with PAI. Can you share your config?

**Comment by martinl** [comment]
Here is the config
```
LOGGING_LEVEL_CONSOLE: 10
LOGGING_LEVEL_FILE: 10
CONNECTION_TYPE: IP
SERIAL_PORT: /dev/ttyUSB0
SERIAL_BAUD: 9600
IP_CONNECTION_HOST: 127.0.0.1
IP_CONNECTION_PORT: 10000
IP_CONNECTION_PASSWORD: xxxxxxx
KEEP_ALIVE_INTERVAL: 100
LIMITS:
  zone: auto
  user: 1-10
  door: ""
  pgm: 1-5
  partition: auto
  module: ""
  repeater: ""
  keypad: ""
  key-switch: ""
SYNC_TIME: true
SYNC_TIME_MIN_DRIFT: 120
PASSWORD: "xxxx"
MQTT_ENABLE: true
MQTT_HOST: core-mosquitto
MQTT_PORT: 1883
MQTT_KEEPALIVE: 60
MQTT_USERNAME: pai
MQTT_PASSWORD: xxxxxxxxxxxxxxxxxxxx
MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE: true
COMMAND_ALIAS:
  arm: partition all arm
  disarm: partition all disarm
MQTT_COMMAND_ALIAS:
  armed_home: arm_stay
  armed_night: arm_sleep
  armed_away: arm
  disarmed: disarm
HOMEASSISTANT_NOTIFICATIONS_EVENT_FILTERS:
  - live,alarm,-restore
  - trouble,-clock
  - live,tamper
HOMEASSISTANT_PUBLISH_PARTITION_PROPERTIES:
  - target_state
  - current_state
HOMEASSISTANT_PUBLISH_ZONE_PROPERTIES:
  - open
  - tamper
PUSHBULLET_CONTACTS: []
PUSHBULLET_EVENT_FILTERS:
  - live,alarm,-restore
  - trouble,-clock
  - live,tamper
PUSHOVER_EVENT_FILTERS:
  - live,alarm,-restore
  - trouble,-clock
  - live,tamper
PUSHOVER_BROADCAST_KEYS: []
SIGNAL_CONTACTS: []
SIGNAL_EVENT_FILTERS:
  - live,alarm,-restore
  - trouble,-clock
  - live,tamper
GSM_CONTACTS: []
GSM_EVENT_FILTERS:
  - live,alarm,-restore
  - trouble,-clock
  - live,tamper
IP_INTERFACE_ENABLE: false
IP_INTERFACE_PASSWORD: xxxxxxx
DUMMY_EVENT_FILTERS: []
IO_TIMEOUT: 10
IP_CONNECTION_SITEID: xxxxxx
IP_CONNECTION_PANEL_SERIAL: xxxxxxxx
PUSH_UPDATE_WITHOUT_CHANGE: true
HOMEASSISTANT_NOTIFICATIONS_ENABLE: true
```

**Comment by yozik04** [comment]
I have added the parameter. You can try, but I do not have high hopes.

**Comment by yozik04** [comment]
Certainly you need to enter email. You can omit panel serial. It will take first one available.
But this is connection through paradox cloud. You can try local connection as well

**Comment by yozik04** [comment]
I assume you have read this: https://github.com/ParadoxAlarmInterface/pai/wiki/Connection-methods#ip-module-connection-IP100-IP150

**Comment by yozik04** [comment]
Closing as **stale**: this issue has had no activity for more than 18 months and could not be reproduced or progressed with the information available.

This is a housekeeping pass, not a judgement on the merit of the request. If this is still relevant on a current PAI release, please comment and it will be reopened, or start a thread in [Discussions](https://github.com/ParadoxAlarmInterface/pai/discussions).
