### ISSUE TITLE
Can't connect to Pannel with error ConnectToIpModuleFailed(f"Reason: {response.login_status}")

### ISSUE THREAD

**Issue by minhsu12113** [ParadoxAlarmInterface/pai#499]
## Alarm system
Access mode IP150

## Environment
 Linux
- Python version 3.8
 
## Describe the bug
Can't connect to panel

## To Reproduce
run script **./run.sh -c pai.conf**

## Logs

> Attempting to load configuration from /home/lovad/pai/pai.conf
2024-09-13 10:19:39,782 - INFO     - PAI - Starting Paradox Alarm Interface 3.4.2-dev
2024-09-13 10:19:39,782 - INFO     - PAI - Config loaded from /home/lovad/pai/pai.conf
2024-09-13 10:19:39,782 - INFO     - PAI - Console Log level set to 20
2024-09-13 10:19:39,783 - INFO     - PAI - Starting...
2024-09-13 10:19:39,783 - INFO     - PAI.paradox.paradox - Connecting to interface
2024-09-13 10:19:39,783 - INFO     - PAI.paradox.paradox - Using IP Connection
2024-09-13 10:19:39,876 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2024-09-13 10:19:39,878 - INFO     - PAI.paradox.connections.connection - Connection established
2024-09-13 10:19:39,878 - INFO     - PAI.paradox.connections.ip.commands - Authenticating with IP Module
2024-09-13 10:19:39,884 - ERROR    - PAI.paradox.connections.ip.commands - Error connecting to IP Module: 173
2024-09-13 10:19:39,884 - ERROR    - PAI.paradox.connections.ip.connection - Unhandled exception while connecting (try 1/3): Reason: 173
Traceback (most recent call last):
  File "/home/lovad/pai/paradox/connections/ip/connection.py", line 28, in connect
    await self._try_connect()
  File "/home/lovad/pai/paradox/connections/ip/connection.py", line 122, in _try_connect
    await IPModuleConnectCommand(self).execute()
  File "/home/lovad/pai/paradox/connections/ip/commands.py", line 16, in execute
    await self._authenticate_to_ip_module()
  File "/home/lovad/pai/paradox/connections/ip/commands.py", line 125, in _authenticate_to_ip_module
    raise ConnectToIpModuleFailed(f"Reason: {response.login_status}")
paradox.exceptions.ConnectToIpModuleFailed: Reason: 173
2024-09-13 10:19:39,884 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 2/3
2024-09-13 10:19:39,887 - INFO     - PAI.paradox.connections.connection - Connection established
2024-09-13 10:19:39,888 - INFO     - PAI.paradox.connections.ip.commands - Authenticating with IP Module
2024-09-13 10:19:39,894 - ERROR    - PAI.paradox.connections.ip.commands - Error connecting to IP Module: 163
2024-09-13 10:19:39,894 - ERROR    - PAI.paradox.connections.ip.connection - Unhandled exception while connecting (try 2/3): Reason: 163
Traceback (most recent call last):
  File "/home/lovad/pai/paradox/connections/ip/connection.py", line 28, in connect
    await self._try_connect()
  File "/home/lovad/pai/paradox/connections/ip/connection.py", line 122, in _try_connect
    await IPModuleConnectCommand(self).execute()
  File "/home/lovad/pai/paradox/connections/ip/commands.py", line 16, in execute
    await self._authenticate_to_ip_module()
  File "/home/lovad/pai/paradox/connections/ip/commands.py", line 125, in _authenticate_to_ip_module
    raise ConnectToIpModuleFailed(f"Reason: {response.login_status}")
paradox.exceptions.ConnectToIpModuleFailed: Reason: 163
2024-09-13 10:19:39,894 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 3/3
2024-09-13 10:19:39,897 - INFO     - PAI.paradox.connections.connection - Connection established
2024-09-13 10:19:39,897 - INFO     - PAI.paradox.connections.ip.commands - Authenticating with IP Module
2024-09-13 10:19:39,903 - ERROR    - PAI.paradox.connections.ip.commands - Error connecting to IP Module: 164
2024-09-13 10:19:39,904 - ERROR    - PAI.paradox.connections.ip.connection - Unhandled exception while connecting (try 3/3): Reason: 164
Traceback (most recent call last):
  File "/home/lovad/pai/paradox/connections/ip/connection.py", line 28, in connect
    await self._try_connect()
  File "/home/lovad/pai/paradox/connections/ip/connection.py", line 122, in _try_connect
    await IPModuleConnectCommand(self).execute()
  File "/home/lovad/pai/paradox/connections/ip/commands.py", line 16, in execute
    await self._authenticate_to_ip_module()
  File "/home/lovad/pai/paradox/connections/ip/commands.py", line 125, in _authenticate_to_ip_module
    raise ConnectToIpModuleFailed(f"Reason: {response.login_status}")
paradox.exceptions.ConnectToIpModuleFailed: Reason: 164
2024-09-13 10:19:39,904 - ERROR    - PAI.paradox.paradox - Failed to connect to interface
2024-09-13 10:19:39,904 - ERROR    - PAI - Unable to connect to alarm
2024-09-13 10:19:42,907 - INFO     - PAI - Starting...
2024-09-13 10:19:42,907 - INFO     - PAI.paradox.paradox - Disconnecting from the Alarm Panel
2024-09-13 10:19:42,907 - INFO     - PAI.paradox.paradox - Clean Session
2024-09-13 10:19:42,908 - INFO     - PAI.paradox.paradox - Connecting to interface
2024-09-13 10:19:42,908 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2024-09-13 10:19:42,910 - INFO     - PAI.paradox.connections.connection - Connection established
2024-09-13 10:19:42,910 - INFO     - PAI.paradox.connections.ip.commands - Authenticating with IP Module
2024-09-13 10:19:42,917 - ERROR    - PAI.paradox.connections.ip.commands - Error connecting to IP Module: 255
2024-09-13 10:19:42,917 - ERROR    - PAI.paradox.connections.ip.connection - Unhandled exception while connecting (try 1/3): Reason: 255
Traceback (most recent call last):
  File "/home/lovad/pai/paradox/connections/ip/connection.py", line 28, in connect
    await self._try_connect()
  File "/home/lovad/pai/paradox/connections/ip/connection.py", line 122, in _try_connect
    await IPModuleConnectCommand(self).execute()
  File "/home/lovad/pai/paradox/connections/ip/commands.py", line 16, in execute
    await self._authenticate_to_ip_module()
  File "/home/lovad/pai/paradox/connections/ip/commands.py", line 125, in _authenticate_to_ip_module
    raise ConnectToIpModuleFailed(f"Reason: {response.login_status}")
paradox.exceptions.ConnectToIpModuleFailed: Reason: 255

**Comment by minhsu12113** [comment]
Lack of password of pc, set it and re-run it work
